import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'

const html = readFileSync(new URL('../public/admin/index.html', import.meta.url), 'utf8')
const app = readFileSync(new URL('../public/admin/app.js', import.meta.url), 'utf8')
const css = readFileSync(new URL('../public/admin/styles.css', import.meta.url), 'utf8')
const routes = readFileSync(new URL('../server/routes/admin-console.js', import.meta.url), 'utf8')
const legacyAdmin = readFileSync(new URL('../server/routes/admin.js', import.meta.url), 'utf8')
const aiOperations = readFileSync(new URL('../server/admin/ai-operations.js', import.meta.url), 'utf8')
const riskAudit = readFileSync(new URL('../server/admin/risk-audit.js', import.meta.url), 'utf8')
const contentSystem = readFileSync(new URL('../server/admin/content-system.js', import.meta.url), 'utf8')
const userDeletion = readFileSync(new URL('../server/admin/user-deletion.js', import.meta.url), 'utf8')
const server = readFileSync(new URL('../server/index.js', import.meta.url), 'utf8')
const mainSite = readFileSync(new URL('../public/src/main.js', import.meta.url), 'utf8')

describe('unified admin console contract', () => {
  it('ships a standalone accessible and responsive administration surface', () => {
    expect(html).toContain('id="adminMain"')
    expect(html).toContain('class="skip-link"')
    expect(html).toContain('aria-modal="true"')
    expect(css).toContain('@media (max-width:760px)')
    expect(css).toContain('min-height:44px')
    expect(css).toContain('prefers-reduced-motion')
    expect(html).not.toContain('旧版管理工具')
    expect(app).not.toContain('/ai/?tab=admin-dashboard')
    expect(server).toContain("app.get('/legacy-admin', (req, res) => res.redirect(308, '/admin/'))")
    expect(mainSite).not.toContain('function renderAdmin()')
    expect(mainSite).not.toContain("case 'admin'")
  })

  it('uses canonical admin APIs and keeps user-facing errors in Chinese', () => {
    expect(app).toContain("api('/api/admin/overview')")
    expect(app).toContain('`/api/admin/users/${userId}`')
    expect(routes).toContain("router.patch('/admin/users/:userId'")
    expect(routes).toContain("router.delete('/admin/users/:userId'")
    expect(app).toContain('id="deleteUserButton"')
    expect(app).toContain('confirm_email:user.email')
    expect(app).toContain("true,user.email")
    expect(userDeletion).toContain("deletion_status = 'anonymized'")
    expect(routes).toContain('translateAdminProfileError')
    expect(app).toContain('运行与风控')
    expect(app).toContain('/operations-detail')
    expect(app).toContain('/runtime`')
    expect(app).toContain('/risk`')
    expect(app).toContain('/subscriptions/${row.dataset.operationsSubscription}')
    expect(css).toContain('.operations-runtime')
    expect(css).toContain('.operations-risk-grid')
  })

  it('centralizes orders, membership notifications and referral settlement', () => {
    expect(html).toContain('data-view="commercial"')
    expect(app).toContain("api('/api/admin/commercial/overview')")
    expect(app).toContain('/api/admin/commercial/orders?')
    expect(app).toContain('/api/admin/membership-expiry-notifications?')
    expect(app).toContain('/api/admin/referrals/commissions?')
    expect(routes).toContain("router.get('/admin/commercial/orders'")
    expect(css).toContain('.segment-tabs')
    expect(css).toContain('.mobile-business-grid')
  })

  it('makes the legacy main-site editor reuse the canonical profile service', () => {
    expect(legacyAdmin).toContain("from '../admin/user-profile.js'")
    expect(legacyAdmin).toContain('updateAdminUserProfile({ actorUserId:req.user.id')
    expect(legacyAdmin).not.toContain('密码至少需要6位')
  })


  it('makes referral settlement idempotent and selects one source order', () => {
    expect(legacyAdmin).toContain('FOR UPDATE')
    expect(legacyAdmin).toContain("referral.status !== 'pending'")
    expect(legacyAdmin).toContain('SELECT latest_order.id FROM orders latest_order')
  })

  it('moves AI runtime governance into the canonical admin console', () => {
    expect(html).toContain('data-view="ai-operations"')
    expect(app).toContain("api('/api/admin/ai/overview')")
    expect(app).toContain('/api/admin/ai/observer-sources/${source.id}/runtime')
    expect(routes).toContain("router.get('/admin/ai/overview'")
    expect(routes).toContain("router.patch('/admin/ai/observer-sources/:id/runtime'")
    expect(routes).toContain("router.post('/admin/ai/observer-sources'")
    expect(routes).toContain("router.post('/admin/ai/observer-source-accounts'")
    expect(routes).toContain("router.delete('/admin/ai/observer-sources/:id'")
    expect(routes).toContain("router.post('/admin/ai/observer-channels'")
    expect(routes).toContain("router.delete('/admin/ai/observer-channels/:id'")
    expect(aiOperations).toContain('getAiRolloutHealth()')
    expect(aiOperations).toContain('getReviewAdminHealth()')
    expect(aiOperations).toContain("redis.smembers('auto:scheduler:keys')")
    expect(css).toContain('.observer-admin-grid')
    expect(app).toContain('openObserverSourceEditor')
    expect(app).toContain('openObserverChannelEditor')
    expect(app).toContain('openObserverSourceAccountEditor')
    expect(app).toContain("api('/api/admin/ai/observer-source-accounts'")
    expect(css).toContain('.field-heading')
  })

  it('moves historical-snapshot model evaluation into the canonical admin console', () => {
    expect(app).toContain('data-ai-tab="model-compare"')
    expect(app).toContain("api('/api/admin/ai/model-compare/setup')")
    expect(app).toContain('/api/admin/ai/model-compare/snapshots?')
    expect(app).toContain("api('/api/admin/ai/model-compare/jobs'")
    expect(app).toContain("data_source:'snapshots'")
    expect(app).toContain('不触发实盘风控或交易')
    expect(routes).toContain("router.get('/admin/ai/model-compare/setup'")
    expect(routes).toContain("router.post('/admin/ai/model-compare/jobs'")
    expect(routes).toContain("router.get('/admin/ai/model-compare/jobs/:jobId'")
    expect(routes).toContain("router.delete('/admin/ai/model-compare/jobs/:jobId'")
    expect(css).toContain('.compare-workspace')
    expect(css).toContain('.compare-result-row')
  })

  it('moves platform model sharing and AI governance into the canonical admin console', () => {
    expect(app).toContain('data-ai-tab="models"')
    expect(app).toContain("api('/api/ai/model-profiles?scope=platform')")
    expect(app).toContain("api('/api/ai/platform-model-policy')")
    expect(app).toContain("api('/api/ai/admin/rollout-health')")
    expect(app).toContain("api('/api/ai/admin/feature-flags'")
    expect(app).toContain('/api/ai/admin/risk-rule-rollouts/${encodeURIComponent(select.dataset.rolloutRule)}')
    expect(app).toContain("api('/api/ai/admin/credentials/rotate'")
    expect(app).toContain("confirm:'CLEAR_VERIFIED_LEGACY_CREDENTIALS'")
    expect(app).toContain('openPlatformModelEditor')
    expect(app).toContain('火山方舟 Agent Plan')
    expect(css).toContain('.platform-model-layout')
    expect(css).toContain('.governance-grid')
  })

  it('moves platform memory governance and publishing into the canonical admin console', () => {
    expect(app).toContain('data-ai-tab="memory"')
    expect(app).toContain("api('/api/ai/admin/platform-experience')")
    expect(app).toContain('/api/ai/admin/platform-experience/policies/${form.dataset.memoryPolicy}')
    expect(app).toContain('/api/ai/admin/platform-experience/${row.dataset.memoryItem}/${action}')
    expect(app).toContain('runtime_token_budget')
    expect(app).toContain('影子评估只记录匹配结果，不注入推理')
    expect(css).toContain('.memory-governance-grid')
    expect(css).toContain('.memory-item-row')
  })

  it('centralizes risk status, decisions and administrator audit records', () => {
    expect(html).toContain('data-view="risk-audit"')
    expect(app).toContain('/api/admin/risk-audit/overview?')
    expect(app).toContain('/api/admin/risk-audit/admin-events?')
    expect(app).toContain("api('/api/admin/risk-audit/global-stop'")
    expect(routes).toContain("router.get('/admin/risk-audit/overview'")
    expect(routes).toContain("router.post('/admin/risk-audit/global-stop'")
    expect(routes).toContain("router.get('/admin/risk-audit/platform-policy'")
    expect(routes).toContain("router.put('/admin/risk-audit/platform-policy'")
    expect(riskAudit).toContain('formatRiskReason(row.reject_code')
    expect(riskAudit).toContain('saveAdminPlatformRiskPolicy')
    expect(app).not.toContain("prompt('请输入开启平台紧急停止")
    expect(app).not.toContain('/ai/?tab=global-risk')
    expect(app).toContain('renderPlatformRiskPolicy')
    expect(css).toContain('.risk-account-list')
    expect(css).toContain('.risk-policy-groups')
  })

  it('centralizes course discovery, feedback triage and release publishing', () => {
    expect(html).toContain('data-view="content-system"')
    expect(app).toContain('/api/admin/content-system/courses?')
    expect(app).toContain('/api/admin/content-system/feedback?')
    expect(app).toContain("api('/api/admin/release-notes'")
    expect(routes).toContain("router.get('/admin/content-system/overview'")
    expect(routes).toContain("router.get('/admin/content-system/courses'")
    expect(routes).toContain("router.get('/admin/content-system/engagement'")
    expect(routes).toContain("router.get('/admin/content-system/videos'")
    expect(routes).toContain("router.post('/admin/content-system/courses'")
    expect(routes).toContain("router.delete('/admin/content-system/courses/:courseId'")
    expect(contentSystem).toContain('getAdminContentSystemOverview')
    expect(contentSystem).toContain('saveAdminCourse')
    expect(contentSystem).toContain('deleteAdminCourse')
    expect(app).toContain('data-new-course')
    expect(app).toContain('openCourseEditor')
    expect(app).toContain('data-content-tab="assets"')
    expect(app).toContain('data-content-tab="engagement"')
    expect(app).toContain('data-content-tab="video"')
    expect(app).toContain("api('/api/admin/content-system/videos')")
    expect(app).toContain("xhr.open('POST','/api/video-upload')")
    expect(app).toContain("api('/api/video-stream'")
    expect(app).toContain("api('/api/admin/content-system/engagement')")
    expect(app).toContain('/api/admin-course-resources?episode=')
    expect(app).toContain("api('/api/admin-course-resources'")
    expect(app).toContain('/api/admin-quiz?episode=')
    expect(app).toContain("api('/api/admin-quiz'")
    expect(app).toContain('options.length<2')
    expect(app).toContain('options.body instanceof FormData')
    expect(app).not.toContain('href="/legacy-admin">新增或编辑课程')
    expect(app).not.toContain('/legacy-admin')
    expect(app).toContain("api('/api/system-config')")
    expect(app).toContain("api('/api/system-config/smtp/test'")
    expect(app).toContain("api('/api/system-config/sms/test'")
    expect(app).toContain("api('/api/admin/crypto/sweep/balances')")
    expect(app).toContain("api('/api/admin/crypto/payment-mode')")
    expect(app).toContain("api('/api/admin/crypto/sweep'")
    expect(app).toContain('确认一键归集？')
    expect(app).toContain('renderSystemConfigCategory')
    expect(app).toContain('data-redacted="true"')
    expect(css).toContain('.content-card-list')
    expect(css).toContain('.course-asset-workspace')
    expect(css).toContain('.quiz-row')
    expect(css).toContain('.leaderboard-row')
    expect(css).toContain('.video-admin-grid')
    expect(css).toContain('.settings-workbench')
    expect(css).toContain('.config-action-panel')
    expect(css).toContain('.crypto-address-row')
  })
})
