import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'

const html = readFileSync(new URL('../public/admin/index.html', import.meta.url), 'utf8')
const app = readFileSync(new URL('../public/admin/app.js', import.meta.url), 'utf8')
const css = readFileSync(new URL('../public/admin/styles.css', import.meta.url), 'utf8')
const routes = readFileSync(new URL('../server/routes/admin-console.js', import.meta.url), 'utf8')
const configRoute = readFileSync(new URL('../server/routes/config.js', import.meta.url), 'utf8')
const legacyAdmin = readFileSync(new URL('../server/routes/admin.js', import.meta.url), 'utf8')
const aiOperations = readFileSync(new URL('../server/admin/ai-operations.js', import.meta.url), 'utf8')
const riskAudit = readFileSync(new URL('../server/admin/risk-audit.js', import.meta.url), 'utf8')
const contentSystem = readFileSync(new URL('../server/admin/content-system.js', import.meta.url), 'utf8')
const userDeletion = readFileSync(new URL('../server/admin/user-deletion.js', import.meta.url), 'utf8')
const server = readFileSync(new URL('../server/index.js', import.meta.url), 'utf8')
const mainSite = readFileSync(new URL('../public/src/main.js', import.meta.url), 'utf8')
const courseRoutes = readFileSync(new URL('../server/routes/courses.js', import.meta.url), 'utf8')
const courseContent = readFileSync(new URL('../public/src/lib/course-content.js', import.meta.url), 'utf8')
const aiLabHtml = readFileSync(new URL('../public/ai/index.html', import.meta.url), 'utf8')

describe('unified admin console contract', () => {
  it('ships a standalone accessible and responsive administration surface', () => {
    expect(html).toContain('id="adminMain"')
    expect(html).toContain('class="skip-link"')
    expect(html).toContain('aria-modal="true"')
    expect(html).toContain('id="adminAccountModal"')
    expect(html).toContain('id="adminAccountFrame"')
    expect(css).toContain('@media (max-width:760px)')
    expect(css).toContain('.admin-account-dialog')
    expect(css).toContain('min-height:44px')
    expect(css).toContain('prefers-reduced-motion')
    expect(html).not.toContain('旧版管理工具')
    expect(app).not.toContain('/ai/?tab=admin-dashboard')
    expect(server).toContain("app.get('/legacy-admin', (req, res) => res.redirect(308, '/admin/'))")
    expect(mainSite).not.toContain('function renderAdmin()')
    expect(mainSite).not.toContain("case 'admin'")
  })

  it('shares the main site theme contract and keeps the operations layout compact', () => {
    expect(html).toContain('<meta name="color-scheme" content="light dark">')
    expect(html).toContain("localStorage.getItem('ws_theme')")
    expect(html).toContain('id="themeToggleButton"')
    expect(app).toContain("const ADMIN_THEME_KEY = 'ws_theme'")
    expect(app).toContain("applyAdminTheme(current === 'dark' ? 'light' : 'dark', { persist:true })")
    expect(css).toContain('html[data-theme="dark"]')
    expect(css).toContain('.theme-toggle-button')
    expect(css).toContain('align-items:start')
    expect(css).toContain('grid-template-columns:minmax(0,1.55fr) minmax(300px,.8fr)')
    expect(html).toContain('id="adminRealtimeStatus"')
    expect(app).toContain('type=admin`')
    expect(app).not.toContain('type=admin&token=')
    expect(html).toContain('/shared/session.js?v=20260812memory4')
    expect(app).toContain('window.AuthSession?.syncCookie()')
    expect(app).toContain("location.protocol === 'https:' ? 'wss:' : 'ws:'")
    expect(app).toContain('scheduleAdminRealtimeReconnect')
    expect(css).toContain('.admin-realtime-status')
    expect(html).not.toContain('topbar-utility-actions')
    expect(html).toContain('icon-button topbar-icon-button theme-toggle-button')
    expect(html).toContain('icon-button topbar-icon-button" id="refreshButton"')
    expect(css).toContain('.topbar-icon-button > [data-icon]')
    expect(css).toContain('overflow:visible')
  })

  it('uses canonical admin APIs and keeps user-facing errors in Chinese', () => {
    expect(app).toContain("api('/api/admin/overview')")
    expect(app).toContain('class="overview-status-band')
    expect(app).toContain('待办与异常')
    expect(app).toContain("state.membership = 'expired'; state.page = 1; setView('users')")
    expect(app).toContain("state.aiTab = 'memory'; setView('ai-operations')")
    expect(css).toContain('.overview-workspace-grid')
    expect(css).toContain('.overview-task-row')
    expect(app).toContain('`/api/admin/users/${userId}`')
    expect(routes).toContain("router.patch('/admin/users/:userId'")
    expect(routes).toContain("router.delete('/admin/users/:userId'")
    expect(app).toContain('id="deleteUserButton"')
    expect(app).toContain('confirm_email:user.email')
    expect(app).toContain("true,user.email")
    expect(userDeletion).toContain("deletion_status = 'anonymized'")
    expect(routes).toContain('translateAdminProfileError')
    expect(app).toContain('运行与风控')
    expect(app).toContain('/operations-detail')
    expect(app).toContain('/runtime`')
    expect(app).toContain('/risk`')
    expect(app).toContain('/subscriptions/${row.dataset.operationsSubscription}')
    expect(css).toContain('.operations-runtime')
    expect(css).toContain('.operations-risk-grid')
  })

  it('provides accessible membership expiry presets in the user editor', () => {
    for (const label of ['半个月', '一个月', '3个月', '一年', '长期有效']) expect(app).toContain(`>${label}</button>`)
    expect(app).toContain('aria-label="快捷设置会员有效期"')
    expect(app).toContain('function adminMembershipExpiryPreset')
    expect(app).toContain("preset === 'long_term'")
    expect(app).toContain('bindMembershipExpiryPresets(body, user.plan)')
    expect(css).toContain('.membership-expiry-presets button[aria-pressed="true"]')
    expect(css).toContain('.membership-expiry-presets button:disabled')
    expect(app).toContain('class="profile-layout"')
    expect(app).toContain('身份资料')
    expect(app).toContain('会员权益')
    expect(app).toContain('账号安全')
    expect(app).toContain('id="profileMembershipPlanState"')
    expect(app).toContain('id="profileMembershipExpiryState"')
    expect(css).toContain('.profile-section-head')
    expect(css).toContain('.profile-form-actions')
  })

  it('keeps the user identity summary in one modal header instead of repeating it in the body', () => {
    expect(html).toContain('id="userModalAvatar"')
    expect(html).toContain('id="userModalMembership"')
    expect(html).toContain('id="userModalMeta"')
    expect(app).toContain("document.querySelector('#userModalAvatar').textContent = displayName.slice(0,1)")
    expect(app).toContain("document.querySelector('#userModalMembership').innerHTML = membershipBadge(user)")
    expect(app).not.toContain('<div class="detail-hero">')
    expect(css).toContain('.user-modal-heading-line')
    expect(css).toContain('.user-modal-meta')
  })

  it('centralizes orders, membership notifications and referral settlement', () => {
    expect(html).toContain('data-view="commercial"')
    expect(app).toContain("api('/api/admin/commercial/overview')")
    expect(app).toContain('/api/admin/commercial/orders?')
    expect(app).toContain('/api/admin/membership-expiry-notifications?')
    expect(app).toContain('/api/admin/referrals/commissions?')
    expect(routes).toContain("router.get('/admin/commercial/orders'")
    expect(css).toContain('.segment-tabs')
    expect(css).toContain('.mobile-business-grid')
  })

  it('keeps commercial values in canonical dollar amounts end to end', () => {
    expect(app).toContain('function formatMoney(amount')
    expect(app).not.toContain('Number(cents || 0) / 100')
    expect(app).toContain('order.confirmed_amount : order.amount')
    expect(app).toContain('item.commission_amount')
    expect(routes).toContain('amount:Number(row.amount || 0)')
    expect(routes).toContain('confirmed_amount:Number(row.amount_confirmed || 0)')
    expect(routes).not.toContain('amount_cents:Number(row.amount || 0)')
    expect(legacyAdmin).toContain('pending_credit_amount: Number(pendingCommission || 0)')
    expect(legacyAdmin).not.toContain('pending * 500')
  })

  it('makes the legacy main-site editor reuse the canonical profile service', () => {
    expect(legacyAdmin).toContain("from '../admin/user-profile.js'")
    expect(legacyAdmin).toContain('updateAdminUserProfile({ actorUserId:req.user.id')
    expect(legacyAdmin).not.toContain('密码至少需要6位')
  })


  it('makes referral settlement idempotent and uses the payment-attributed source order', () => {
    expect(legacyAdmin).toContain('FOR UPDATE')
    expect(legacyAdmin).toContain("referral.status !== 'pending'")
    expect(legacyAdmin).toContain('LEFT JOIN orders o ON o.order_id = r.order_id')
    expect(legacyAdmin).not.toContain('SELECT latest_order.id FROM orders latest_order')
  })

  it('moves AI runtime governance into the canonical admin console', () => {
    expect(html).toContain('data-view="ai-operations"')
    expect(app).toContain('class="ai-ops-masthead"')
    expect(app).toContain('class="ai-ops-nav"')
    expect(app).toContain('id="aiOpsRealtimeLastAt"')
    expect(app).toContain('function updateAiOpsTerminalClock(value, userId = 0, platform = \'\', timezoneOffsetMinutes = null)')
    expect(app).toContain('data-terminal-platform-label')
    expect(app).toContain('message.data?.platform')
    expect(app).toContain('timestamp + offset * 60_000')
    expect(app).toContain("connectedMt4 > 0 && connectedMt5 === 0 ? 'mt4'")
    expect(app).toContain('updateAiOpsTerminalClock(clock.time, clock.user_id, connectedPlatform, clock.timezone_offset_minutes)')
    expect(app).toContain("message.reason === 'tick'")
    expect(app).toContain('patchSchedulerRealtime(message)')
    expect(app).not.toContain('ai-ops-nav-group')
    expect(app).toContain('data-ai-jump="scheduler"')
    expect(app).not.toContain('data-ai-tab="strategies"')
    expect(app).not.toContain('data-ai-tab="models"')
    expect(app).toContain('data-ai-tab="memory"')
    expect(aiLabHtml).toContain('data-tab="model-strategy"')
    expect(aiLabHtml).toContain('data-tab="review-memory"')
    expect(css).toContain('.ai-command-status')
    expect(css).toContain('.ai-runtime-strip')
    expect(app).toContain("api('/api/admin/ai/overview')")
    expect(app).toContain('/api/admin/ai/observer-sources/${source.id}/runtime')
    expect(routes).toContain("router.get('/admin/ai/overview'")
    expect(routes).toContain("router.patch('/admin/ai/observer-sources/:id/runtime'")
    expect(routes).toContain("router.post('/admin/ai/observer-sources'")
    expect(routes).toContain("router.post('/admin/ai/observer-source-accounts'")
    expect(routes).toContain("router.delete('/admin/ai/observer-sources/:id'")
    expect(routes).toContain("router.post('/admin/ai/observer-channels'")
    expect(routes).toContain("router.delete('/admin/ai/observer-channels/:id'")
    expect(aiOperations).toContain('getAiRolloutHealth()')
    expect(aiOperations).toContain('getReviewAdminHealth()')
    expect(aiOperations).toContain("redis.smembers('auto:scheduler:keys')")
    expect(css).toContain('.observer-admin-grid')
    expect(app).toContain('openObserverSourceEditor')
    expect(app).toContain('openObserverChannelEditor')
    expect(app).toContain('openObserverSourceAccountEditor')
    expect(app).toContain("api('/api/admin/ai/observer-source-accounts'")
    expect(css).toContain('.field-heading')
  })

  it('moves historical-snapshot model evaluation into the canonical admin console', () => {
    expect(app).toContain('data-ai-tab="model-compare"')
    expect(app).toContain("api('/api/admin/ai/model-compare/setup')")
    expect(app).toContain('/api/admin/ai/model-compare/snapshots?')
    expect(app).toContain("api('/api/admin/ai/model-compare/jobs'")
    expect(app).toContain("data_source:'snapshots'")
    expect(app).toContain('不触发实盘风控或交易')
    expect(routes).toContain("router.get('/admin/ai/model-compare/setup'")
    expect(routes).toContain("router.post('/admin/ai/model-compare/jobs'")
    expect(routes).toContain("router.get('/admin/ai/model-compare/jobs/:jobId'")
    expect(routes).toContain("router.delete('/admin/ai/model-compare/jobs/:jobId'")
    expect(css).toContain('.compare-workspace')
    expect(css).toContain('.compare-result-row')
  })

  it('keeps model configuration in the AI lab instead of the operations console', () => {
    expect(app).not.toContain('data-ai-tab="models"')
    expect(routes).not.toContain("router.get('/admin/ai/models'")
    expect(aiLabHtml).toContain('data-model-strategy-tab="models"')
    expect(app).toContain("api('/api/ai/platform-model-policy')")
    expect(app).toContain("api('/api/ai/admin/rollout-health')")
    expect(app).toContain("api('/api/ai/admin/feature-flags'")
    expect(app).toContain('/api/ai/admin/risk-rule-rollouts/${encodeURIComponent(select.dataset.rolloutRule)}')
    expect(app).toContain("api('/api/ai/admin/credentials/rotate'")
    expect(app).toContain("confirm:'CLEAR_VERIFIED_LEGACY_CREDENTIALS'")
    expect(app).toContain('openPlatformModelEditor')
    expect(app).toContain('火山方舟 Agent Plan')
    expect(css).toContain('.platform-model-layout')
    expect(css).toContain('.governance-grid')
  })

  it('keeps strategy lifecycle management in the AI lab instead of the operations console', () => {
    expect(app).not.toContain('data-ai-tab="strategies"')
    expect(aiLabHtml).toContain('data-model-strategy-tab="strategies"')
    expect(app).toContain("api('/api/admin/ai/strategies')")
    expect(routes).toContain("listStrategies(req.user.id, req.user.role, { scope:'platform', includeInactive:true })")
    expect(app).toContain('openPlatformStrategyEditor')
    expect(app).toContain('data-platform-timeframe')
    expect(app).toContain('data-platform-entry')
    expect(app).toContain('confirm_stop_subscriptions:true')
    expect(routes).toContain("router.get('/admin/ai/strategies'")
    expect(routes).toContain("router.post('/admin/ai/strategies'")
    expect(routes).toContain("router.put('/admin/ai/strategies/:id'")
    expect(routes).toContain("router.get('/admin/ai/strategies/:id/delete-preview'")
    expect(routes).toContain("router.delete('/admin/ai/strategies/:id'")
    expect(css).toContain('.platform-strategy-list')
    expect(css).toContain('.strategy-governance-editor')
  })

  it('keeps review work in the AI lab while exposing platform memory governance in operations', () => {
    expect(app).toContain('data-ai-tab="memory"')
    expect(aiLabHtml).toContain('data-workspace-tab="review-memory"')
    expect(app).toContain("api('/api/ai/strategy-memories')")
    expect(app).toContain('function renderPlatformMemory()')
    expect(app).toContain('id="platformStrategyMemoryEditor"')
    expect(app).toContain('data-platform-memory-compress')
    expect(app).not.toContain("api('/api/ai/admin/platform-experience')")
    expect(app).toContain("api('/api/ai/period-reviews?limit=50')")
    expect(app).toContain('openPlatformReview')
    expect(app).toContain('/confirm`,{method:\'POST\'')
    expect(app).toContain('完整记忆库（Markdown）')
    expect(css).toContain('.platform-review-list')
  })

  it('keeps admin risk management focused while decisions and system audit remain in the AI lab', () => {
    expect(html).toContain('data-view="risk-audit"')
    expect(html).toContain('风控管理')
    expect(app).toContain('/api/admin/risk-audit/overview?')
    expect(app).toContain("api('/api/admin/risk-audit/global-stop'")
    expect(routes).toContain("router.get('/admin/risk-audit/overview'")
    expect(routes).toContain("router.post('/admin/risk-audit/global-stop'")
    expect(routes).toContain("router.get('/admin/risk-audit/platform-policy'")
    expect(routes).toContain("router.put('/admin/risk-audit/platform-policy'")
    expect(riskAudit).not.toContain('formatRiskReason(row.reject_code')
    expect(riskAudit).toContain('saveAdminPlatformRiskPolicy')
    expect(routes).toContain('accountPage:req.query.account_page')
    expect(app).toContain('account_pagination')
    expect(app).toContain('riskAccountPagination')
    expect(app).toContain('已切换账户统一排在最后')
    expect(css).toContain('.risk-account-grid-head')
    expect(app).not.toContain('data-risk-tab="decisions"')
    expect(app).not.toContain('data-risk-tab="audit"')
    expect(aiLabHtml).toContain('data-workspace-target="decisions"')
    expect(aiLabHtml).toContain('风控记录')
    expect(aiLabHtml).toContain('data-tab="audit"')
    expect(aiLabHtml).toContain('系统审计')
    expect(app).not.toContain("prompt('请输入开启平台紧急停止")
    expect(app).not.toContain('/ai/?tab=global-risk')
    expect(app).toContain('renderPlatformRiskPolicy')
    expect(css).toContain('.risk-account-list')
    expect(app).not.toContain('risk-policy-groups')
    expect(css).toContain('.risk-policy-matrix')
    expect(css).toContain('.risk-policy-console')
  })

  it('centralizes course discovery, feedback triage and release publishing', () => {
    expect(html).toContain('data-view="content-operations"')
    expect(html).toContain('data-view="system-settings"')
    expect(app).toContain('/api/admin/content-system/courses?')
    expect(app).toContain('/api/admin/content-system/feedback?')
    expect(app).toContain("api('/api/admin/release-notes'")
    expect(routes).toContain("router.get('/admin/content-system/overview'")
    expect(routes).toContain("router.get('/admin/content-system/courses'")
    expect(routes).toContain("router.get('/admin/content-system/engagement'")
    expect(routes).toContain("router.get('/admin/content-system/videos'")
    expect(routes).toContain("router.post('/admin/content-system/courses'")
    expect(routes).toContain("router.delete('/admin/content-system/courses/:courseId'")
    expect(contentSystem).toContain('getAdminContentSystemOverview')
    expect(contentSystem).toContain('saveAdminCourse')
    expect(contentSystem).toContain('deleteAdminCourse')
    expect(app).toContain('data-new-course')
    expect(app).toContain('openCourseEditor')
    expect(app).toContain("{id:'assets',label:'课件与测验'")
    expect(app).toContain("{id:'engagement',label:'学习数据'")
    expect(app).toContain("{id:'video',label:'视频管理'")
    expect(app).toContain("api('/api/admin/content-system/videos')")
    expect(app).toContain("xhr.open('POST','/api/video-upload')")
    expect(app).toContain("api('/api/video-storage-provider')")
    expect(app).toContain("api('/api/video-upload-session'")
    expect(app).toContain("api('/api/video-upload-confirm'")
    expect(app).not.toContain("api('/api/video-stream',{method:'POST'")
    expect(app).toContain("api('/api/admin/content-system/engagement')")
    expect(app).toContain('/api/admin-course-resources?episode=')
    expect(app).toContain("api('/api/admin-course-resources'")
    expect(app).toContain("xhr.open('POST','/api/admin-course-attachments')")
    expect(app).toContain('/api/admin-course-attachments/${attachmentId}')
    expect(app).toContain('课件与测验工作台')
    expect(app).toContain('课程附件')
    expect(app).toContain('/api/admin-quiz?episode=')
    expect(app).toContain("api('/api/admin-quiz'")
    expect(app).toContain('options.length<2')
    expect(app).toContain('options.body instanceof FormData')
    expect(app).not.toContain('href="/legacy-admin">新增或编辑课程')
    expect(app).not.toContain('/legacy-admin')
    expect(app).toContain("api('/api/system-config')")
    expect(app).toContain("api('/api/system-config/smtp/test'")
    expect(app).toContain("api('/api/system-config/sms/test'")
    expect(app).toContain('固定地址 TRC-20')
    expect(app).toContain('执行合约已锁定')
    expect(app).toContain('renderSystemConfigCategory')
    expect(app).toContain('data-redacted="true"')
    expect(app).toContain('systemCategoryMeta')
    expect(app).not.toContain('title="系统字段：')
    expect(app).toContain("enable_email_login:'允许邮箱登录'")
    expect(app).toContain('systemConfigDirty')
    expect(app).toContain('有未保存的修改')
    expect(app).toContain('敏感内容已加密保护')
    expect(app).toContain('没有匹配的配置')
    expect(app).toContain("function structuredConfigInput(category,item,index)")
    expect(app).toContain("category==='market_menu'")
    expect(app).toContain('data-structured-add-group')
    expect(app).toContain('data-structured-add-item')
    expect(app).toContain('推广与补充信息')
    expect(app).toContain('syncStructuredConfig(editor)')
    expect(app).toContain('function planPricesEditorHtml(items)')
    expect(app).toContain('所有金额均为美元')
    expect(app).toContain('用户实际支付金额')
    expect(app).toContain('仅用于主站划线价展示')
    expect(app).toContain('refreshPlanPriceSummaries(root)')
    expect(css).toContain('.structured-config-editor')
    expect(css).toContain('.structured-config-row-actions button:focus-visible')
    expect(css).toContain('.plan-price-cycle')
    expect(css).toContain('.plan-price-calculation')
    expect(css).toContain('System settings readability pass')
    expect(css).toContain('.system-settings-page .config-field-copy label { font-size:14px; }')
    expect(css).toContain('.system-settings-page .input,')
    expect(css).toContain('.system-settings-page .system-workbench small,')
    expect(app).toContain('邮箱（可选）')
    expect(app).toContain('已有联系方式的账号至少保留一项')
    expect(app).not.toContain('id="profileEmail" name="email" type="email" required')
    expect(css).toContain('.content-workspace-tabs')
    expect(css).toContain('.course-operations-row')
    expect(css).toContain('.course-attachment-admin-row')
    expect(css).toContain('.course-asset-workspace')
    expect(css).toContain('.quiz-row')
    expect(css).toContain('.leaderboard-row')
    expect(css).toContain('.video-admin-grid')
    expect(app).toContain('内容交付中枢')
    expect(app).toContain('content-workbench-shell')
    expect(app).toContain('content-feedback-panel')
    expect(app).toContain('content-learning-summary')
    expect(app).toContain('content-video-library')
    expect(html).toContain('course-editor-modal-title')
    expect(app).toContain('course-publish-preview')
    expect(app).toContain('course-editor-action-note')
    expect(app).toContain('updateModalState')
    expect(app).toContain("#contentModal [data-close-content-modal]")
    expect(app).not.toContain('id="courseYoutube"')
    expect(app).not.toContain('YouTube 视频编号')
    expect(app).toContain("youtube_id:String(course.youtube_id||'')")
    expect(css).toContain('premium editorial command center')
    expect(css).toContain('.content-learning-summary')
    expect(css).toContain('.content-feedback-toolbar')
    expect(css).toContain('--scrollbar-track: #f2efe8')
    expect(css).toContain('--scrollbar-thumb: #334155')
    expect(css).toContain('Course editor modal / focused publishing workspace')
    expect(html).toContain('/admin/styles.css?v=20260812memory4')
    expect(html).toContain('/admin/app.js?v=20260812memory4')
    expect(app).toContain('function filterSubmitButton')
    expect(app.match(/filterSubmitButton\(\)/g)).toHaveLength(4)
    expect(css).toContain('.filter-bar { align-items:end; gap:8px; padding:12px 16px;')
    expect(css).toContain('.filter-submit-button { min-width:88px; min-height:38px; align-self:end;')
    expect(css).toContain('.settings-workbench')
    expect(css).toContain('.config-action-panel')
    expect(css).toContain('.crypto-address-row')
    expect(css).toContain('.system-overview-strip')
    expect(css).toContain('.system-config-savebar')
    expect(css).toContain('.config-toggle-control')
    expect(css).toContain('.config-secret-state')
    expect(css).toContain('.config-readonly-value')
  })

  it('keeps release-note editing server-sanitized, revision-aware and notification-safe', () => {
    expect(configRoute).toContain("router.get('/changelog/current'")
    expect(configRoute).toContain("router.get('/admin/release-notes'")
    expect(configRoute).toContain("router.post('/admin/release-notes/preview'")
    expect(configRoute).toContain('withTransaction')
    expect(configRoute).toContain('FOR UPDATE')
    expect(configRoute).toContain('expectedRevision')
    expect(configRoute).toContain('release_notes_updated')
    expect(configRoute).toContain('releaseNotesRevision')
    expect(app).toContain('通知序号')
    expect(app).toContain('release-version-field')
    expect(app).toContain('release-content-field')
    expect(app).toContain('release-content-count')
    expect(app).toContain('/api/admin/release-notes/preview')
    expect(app).toContain('expected_revision:state.releaseNotesRevision')
    expect(app).toContain('releaseNotificationImpact')
    expect(app).toContain('releasePreviewRemoved')
    expect(app).toContain('服务端白名单净化')
    expect(css).toContain('.release-preview-panel')
    expect(css).toContain('.release-notification-impact')
    expect(css).toContain('grid-template-columns:minmax(180px,.46fr) minmax(280px,1fr) auto')
    expect(css).toContain('.system-release-form .release-content-count')
    expect(css).not.toContain('.system-release-form .field small {')
    expect(aiLabHtml).not.toContain('function sanitizeHtml(html)')
    expect(app).toContain('current.content')
  })

  it('exposes compact AI governance, referral rules and a dedicated management audit view', () => {
    expect(html).toContain('data-view="management-audit"')
    expect(app).toContain('data-ai-tab="governance"')
    expect(app).toContain("api('/api/ai/admin/rollout-health')")
    expect(app).toContain("api('/api/ai/admin/position-management-settings')")
    expect(app).toContain("api('/api/ai/admin/position-management-control'")
    expect(app).not.toContain("/api/ai/admin/position-management-rollouts/")
    expect(app).not.toContain('账户执行授权')
    expect(app).toContain('自动平仓')
    expect(app).not.toContain("platform.maximum_mode==='shadow'")
    expect(app).not.toContain('自动退出并反转（尚未开放）')
    expect(app).not.toContain('positionRolloutDailyLimit')
    expect(app).not.toContain('positionRolloutCooldown')
    expect(app).toContain("api('/api/admin/referrals/rules')")
    expect(app).toContain("renderAuditEvents('managementAuditContent')")
    expect(app).toContain("params.set('target_type',state.auditTarget)")
    expect(app).toContain('item.details||item.change_summary')
    expect(app).not.toContain('auditSensitiveDetailKey')
    expect(app).toContain('audit-summary-strip')
    expect(app).toContain('audit-event-card')
    expect(css).toContain('.audit-filter-panel')
    expect(css).toContain('.audit-technical-evidence')
    expect(app).toContain('contentHealthPanel')
    expect(app).toContain('AI 核心链路存在严重异常')
    expect(app).toContain("数据不足")
    expect(css).toContain('.audit-detail-grid')
    expect(css).toContain('.audit-integrity-card')
    expect(app).toContain('自动执行器未就绪')
    expect(app).toContain('分别控制自动平仓、新增 AI 挂单和 AI 取消挂单，三项能力互不联动')
    expect(app).toContain("id:'positionAiPendingOrder'")
    expect(app).toContain("id:'positionAiPendingCancel'")
    expect(app).toContain("id:'positionAutoExit'")
    expect(app).toContain('id="governancePolicyDirty"')
    expect(app).toContain('id="governanceFeatureDirty"')
    expect(app).not.toContain('id="positionBlockNewRisk"')
    expect(app).not.toContain('id="positionFreezeAutomatic"')
    expect(app).not.toContain('id="positionEmergencyFlatten"')
    expect(app).not.toContain('auto_cancel')
    expect(css).toContain('.governance-status-strip')
    expect(css).toContain('.governance-status-card')
    expect(css).toMatch(/\.governance-status-strip \.governance-status-icon\s*\{[^}]*display:grid;[^}]*place-items:center;[^}]*line-height:0;/s)
    expect(css).toMatch(/\.governance-status-strip \.governance-status-icon svg\s*\{[^}]*display:block;/s)
    expect(css).toContain('.governance-rollout-list')
    expect(css).toContain('max-height:none')
    expect(css).toContain('.referral-rule-grid')
  })

  it('delivers protected downloadable course attachments to the main course detail', () => {
    expect(legacyAdmin).toContain("router.post('/admin-course-attachments'")
    expect(legacyAdmin).toContain("router.delete('/admin-course-attachments/:attachmentId'")
    expect(courseRoutes).toContain("router.get('/course-items/:id/attachments'")
    expect(courseRoutes).toContain("router.get('/course-items/:id/attachments/:attachmentId/download'")
    expect(courseRoutes).toContain('canAccessMembershipLevel(req.user, attachment.access_level)')
    expect(courseRoutes).toContain("res.set('X-Content-Type-Options', 'nosniff')")
    expect(courseContent).toContain('loadAttachments(episodeId)')
    expect(mainSite).toContain('courseAttachmentRegionHtml(ep)')
    expect(mainSite).toContain('data-course-attachment-download')
    expect(mainSite).toContain('api.fetchBlobUrl(url)')
  })

  it('keeps scheduler countdowns absolute and calibrates the live admin channel', () => {
    expect(app).toContain('function schedulerRemainingSeconds')
    expect(app).toContain('next_run_at_utc')
    expect(app).not.toContain('item.next_run_in_seconds) - 1')
    expect(app).toContain("message.type === 'admin_pong'")
    expect(app).toContain('adminPongWatchdogTimer')
    expect(app).toContain('calibrateSchedulerRuntimeSilently()')
    expect(app).toContain("message.reason === 'scheduler_state'")
    expect(app).toContain('aiOperationsRequestSeq')
    expect(app).toContain('AbortController')
    expect(app).toContain('<small>正在推理</small>')
    expect(html).toContain('/admin/app.js?v=20260812memory4')
  })
})
