import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'

describe('Python Bridge history contract', () => {
  it('publishes the MT5 terminal algorithm-trading switch with account snapshots', () => {
    const source = readFileSync(new URL('../bridge/adapters/mt5-python/worker.py', import.meta.url), 'utf8')
    expect(source).toContain('account["terminal_trade_allowed"] = bool(')
    expect(source).toContain('identity["terminal"].get("trade_allowed", False)')
  })

  it('isolates named Bridge profiles for multi-source operation', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _resolve_bridge_profile(argv=None):')
    expect(source).toContain('AURUM_BRIDGE_PROFILE')
    expect(source).toContain('profile_config_dir(CONFIG_ROOT, BRIDGE_PROFILE)')
    expect(source).toContain('app = QApplication(QT_ARGV)')
  })

  it('manages one runtime per profile without restoring a global single-instance lock', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const runtime = readFileSync(new URL('../public/ai/bridge_profile_runtime.py', import.meta.url), 'utf8')
    const launcher = readFileSync(new URL('../public/ai/bridge_source_launcher.py', import.meta.url), 'utf8')
    expect(source).toContain('BRIDGE_PROFILE, QT_ARGV')
    expect(source).toContain('acquire_instance_mutex(f"profile-{BRIDGE_PROFILE}")')
    expect(source).toContain('write_profile_runtime')
    expect(runtime).toContain('profile_registry.json')
    expect(launcher).toContain('class NewObserverSourceDialog(QDialog)')
    expect(launcher).toContain('CREATE_NEW_CONSOLE')
    expect(source).not.toContain('BridgeProfileManager')
    expect(runtime).toContain('_instance_mutex_exists(f"profile-{profile}")')
    expect(runtime).toContain('"stale_pid_reused": True')
    expect(runtime).toContain('OpenProcess.restype = ctypes.wintypes.HANDLE')
    expect(runtime).toContain('CreateMutexW.restype = ctypes.wintypes.HANDLE')
    expect(runtime).toContain('OpenMutexW.restype = ctypes.wintypes.HANDLE')
    expect(runtime).toContain('EnumWindows.argtypes = [callback_type, ctypes.wintypes.LPARAM]')
  })

  it('lets only the administrator main Bridge provision a dedicated observer source and MT5 process', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('self.btn_observer_sources = QPushButton("观摩源 ▾")')
    expect(source).toContain('cfg.get("role") == "admin" and BRIDGE_PROFILE == "default"')
    expect(source).toContain('plan_source != "observer_source"')
    expect(source).toContain('find_mt5_path_owner(CONFIG_ROOT, mt5_path)')
    expect(source).toContain('find_source_account_owner(CONFIG_ROOT, values["account"])')
    expect(source).toContain('"auto_start_bridge": True')
    expect(source).toContain('"mt5_portable": False')
    expect(source).toContain('self._mt5_call(self.mt5.initialize, candidate, portable=portable)')
    expect(source).toContain('f"{server.rstrip(\'/\')}/api/auth/me", timeout=5, token=token, parent=self')
    expect(source).toContain('def _show_observer_sources_menu(self):')
    expect(source).toContain('def _open_saved_observer_source(self, slug):')
    expect(source).toContain('activate_profile_window(runtime.get("pid"))')
  })

  it('discovers MT5 installations without a command shell or leaked registry handles', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('def _find_mt5_installations():')
    const end = source.indexOf('\n    def run(self):', start)
    const block = source.slice(start, end)
    expect(source).toContain('def running_mt5_process_directories():')
    expect(source).toContain('CreateToolhelp32Snapshot')
    expect(source).toContain('QueryFullProcessImageNameW')
    expect(block).not.toContain('subprocess.check_output')
    expect(block).toContain('with winreg.OpenKey(')
    expect(block).not.toContain('shell=True')
  })

  it('provides a compact incremental risk snapshot without full-history export', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('def _risk_snapshot')
    const end = source.indexOf('def _process_command', start)
    const block = source.slice(start, end)
    expect(block).toContain('history_deals_get(date_from, date_to)')
    expect(block).toContain('history_deals_get(position=position_id)')
    expect(block).toContain('requested_cursor')
    expect(block).toContain('closed_positions')
    expect(block).toContain('account_events')
    expect(block).toContain('order_calc_profit')
    expect(block).toContain('order_calc_margin')
    expect(block).not.toContain('FULL_HISTORY_START')
  })
  it('reads the profile account creation time and both expiry field styles', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('userData.get("planExpiresAt") or userData.get("plan_expires_at", "")')
    expect(source).toContain('userData.get("accountCreatedAt")')
    expect(source).toContain('self.account_created_at =')
  })

  it('refreshes Bridge authentication without treating transient membership checks as expiry', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _renew_access_token(self, force=False):')
    expect(source).toContain('/api/auth/bridge-refresh')
    expect(source).toContain('/api/auth/bridge-session')
    expect(source).toContain('self._token_expires_within(self.token)')
    expect(source).toContain('return "unknown", False, f"会员状态暂时无法确认')
    expect(source).toContain('"client": "bridge"')
  })

  it('stops reconnecting after the MT5 account is transferred to another platform user', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('if e.code == 4004:')
    expect(source).toContain('getattr(ws, "close_code", None) == 4004')
    expect(source).toContain('MT5账户已由另一个平台账号连接')
    expect(source.indexOf('if e.code == 4004:')).toBeLessThan(source.indexOf('if e.code == 4003:'))
  })

  it('treats an empty date filter as full account history', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const historyStart = source.indexOf('elif action == "history"')
    const chartStart = source.indexOf('elif action == "chart_data"', historyStart)
    const block = source.slice(historyStart, chartStart)
    expect(source).toContain('FULL_HISTORY_START = datetime(2000, 1, 1)')
    expect(block).toContain('date_from = FULL_HISTORY_START')
    expect(block).not.toContain('else: date_from = date_to - timedelta(days=31)')
  })

  it('uses the same full-history default for chart totals', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const chartStart = source.indexOf('elif action == "chart_data"')
    const block = source.slice(chartStart)
    expect(block).toContain('date_from = FULL_HISTORY_START')
    expect(block).not.toContain('date_from = date_to - timedelta(days=31)')
  })

  it('includes trading fees in history net profit and account statistics', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const historyStart = source.indexOf('elif action == "history"')
    const chartStart = source.indexOf('elif action == "chart_data"', historyStart)
    const block = source.slice(historyStart, chartStart)
    expect(block).toContain('"fee": d.get("fee")')
    expect(block).toContain('"net_profit": float(d.get("profit") or 0) + float(d.get("swap") or 0) + float(d.get("commission") or 0) + float(d.get("fee") or 0)')
    expect(block).toContain('tp = sum(float(r.get("net_profit") or 0) for r in rows)')
  })

  it('reuses one deal range and only reads order details for the visible page', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _history_deals_for_range(self, date_from, date_to, force_refresh=False):')
    expect(source).toContain('age <= 15.0 and (not force_refresh or age <= 1.0)')
    const historyStart = source.indexOf('elif action == "history"')
    const chartStart = source.indexOf('elif action == "chart_data"', historyStart)
    const block = source.slice(historyStart, chartStart)
    expect(block).toContain('orders = self.mt5.history_orders_get(date_from, date_to) if include_deals else None')
    expect(block).toContain('for row in pr:')
    expect(block).toContain('history_orders_get(ticket=int(row.get("ticket") or 0))')
  })

  it('uses fee-inclusive net profit in chart aggregation', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const chartStart = source.indexOf('elif action == "chart_data"')
    const block = source.slice(chartStart)
    expect(block).toContain('float(d.get("commission") or 0) + float(d.get("fee") or 0)')
    expect(block).toContain('"history_cache_hit": history_cache_hit')
  })

  it('exports raw MT5 attribution fields only when explicitly requested', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const historyStart = source.indexOf('elif action == "history"')
    const chartStart = source.indexOf('elif action == "chart_data"', historyStart)
    const block = source.slice(historyStart, chartStart)
    expect(block).toContain('params.get("include_deals", False)')
    expect(block).toContain('page_size = min(page_size, 10_000)')
    for (const field of ['"position_id"', '"deal_ticket"', '"entry"', '"magic"', '"reason"', '"commission"', '"swap"', '"fee"']) {
      expect(block).toContain(field)
    }
  })

  it('enforces the server trade switch and broker volume constraints before opening exposure', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _validate_order_volume(info, volume):')
    expect(source).toContain('if not self._trade_enabled:')
    expect(source).toContain('volume_error = self._validate_order_volume(info, volume)')
    expect(source).toContain('volume {volume} exceeds broker maximum')
    expect(source).toContain('volume {volume} does not match broker step')
  })

  it('never treats a non-DONE MT5 ticket as confirmed execution', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('classification = classify_deal_result(result, self.mt5)')
    expect(source).toContain('"status": "uncertain"')
    expect(source).toContain('remaining = self.mt5.positions_get(ticket=pos.ticket)')
    expect(source).not.toContain('订单已成交但返回码非DONE')
  })

  it('serializes command and publisher access to the non-thread-safe MT5 extension', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('ThreadPoolExecutor(')
    expect(source).toContain('max_workers=1, thread_name_prefix="aurum-mt5"')
    expect(source).toContain('self._mt5_call(self._import_mt5_module)')
    expect(source).toContain('self._mt5_call(self.mt5.initialize')
    expect(source).toContain('run_in_executor(self._mt5_executor, self._collect_mt5_data)')
    expect(source).toContain('run_in_executor(self._mt5_executor, self._process_command, msg)')
    expect(source).toContain('self._mt5_lock = threading.RLock()')
    expect(source).toContain('with self._mt5_lock:')
    expect(source).toContain('result = self._process_command_locked(cmd)')
    expect(source).toContain('return self._collect_mt5_data_locked()')
  })

  it('normalizes broker wall-clock timestamps while retaining the raw MT5 timestamp', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _calibrate_mt5_clock(self, tick, force=False):')
    expect(source).toContain('DEFAULT_MT5_TIMEZONE_OFFSET_MINUTES = 180')
    expect(source).toContain('if previous_raw_ms == raw_ms:')
    expect(source).toContain('raw_progress_ms = raw_ms - previous_raw_ms')
    expect(source).toContain('abs(raw_progress_ms - host_progress_ms) > MT5_CLOCK_FRESHNESS_TOLERANCE_MS')
    expect(source).toContain('"mt5_timezone_offset_version": 2')
    expect(source).toContain('update_config({"mt5_timezone_offset_minutes": candidate')
    expect(source).toContain('"time_utc_msc": raw_ms - offset * 60000')
    expect(source).toContain('"timezone_offset_minutes": offset')
    expect(source).toContain('"clock_status": self._mt5_clock_status')
  })

  it('detects market state next to MT5 and publishes it in data and heartbeats', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _detect_market_state(self, symbol, info, tick, terminal_info=None):')
    expect(source).toContain('terminal = self.mt5.terminal_info()')
    expect(source).toContain('info = self.mt5.symbol_info(sym)')
    expect(source).toContain('"market_state_version": 1')
    expect(source).toContain('"market_state": state')
    expect(source).toContain('"symbol_trade_mode": trade_mode')
    expect(source).toContain('"tick_progressing": tick_progressing')
    expect(source).toContain('observation.get("confirmed_open") and unchanged_seconds < 60')
    expect(source).toContain('**(self._last_market_state or {})')
    expect(source).toContain('market_fields = self._detect_market_state(sym, info, tick, terminal)')
    expect(source).toContain('elif action == "market_state":')
    expect(source).toContain('self._detect_market_state(symbol, info, tick, terminal)')
  })

  it('rejects invalid pending expirations and reports MT5 pending-list failures', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('"message": "invalid pending order expiration"')
    expect(source).toContain('"message": f"orders_get failed: {self.mt5.last_error()}"')
    expect(source).not.toContain('except:')
  })

  it('reports an exact pending terminal state for guarded cancellation reconciliation', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('elif action == "pending_order_state":')
    const end = source.indexOf('elif action == "symbols":', start)
    const block = source.slice(start, end)
    expect(start).toBeGreaterThan(0)
    expect(block).toContain('self.mt5.orders_get(ticket=ticket)')
    expect(block).toContain('self.mt5.history_orders_get(ticket=ticket)')
    expect(block).toContain('ORDER_STATE_FILLED')
    expect(block).toContain('ORDER_STATE_CANCELED')
    expect(block).toContain('"partially_filled"')
  })

  it('prechecks stop-limit orders and uses the official MT5 request field', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const pendingStart = source.indexOf('elif action == "pending"')
    const cancelStart = source.indexOf('elif action == "cancel_pending"', pendingStart)
    const block = source.slice(pendingStart, cancelStart)
    expect(block).toContain('stoplimit_price, "stoplimit price", required=True')
    expect(block).toContain('req["stoplimit"] = stoplimit_price')
    expect(block).toContain('check = self.mt5.order_check(req)')
    expect(block).toContain('"status": "rejected"')
    expect(block).toContain('"retcode": result.retcode')
  })

  it('fails closed when an execution command omits volume or close ticket', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('parse_required_order_volume(params)')
    expect(source).not.toContain('params.get("lot") or params.get("volume") or 0.01')
    expect(source).toContain('"message": "ticket is required"')
  })

  it('removes unused high-authority management commands and guards generic mutations', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).not.toContain('elif action == "close_all":')
    expect(source).not.toContain('elif action == "modify":')
    expect(source).not.toContain('def _order_send_simple_retry(')
    expect(source).toContain('"position", required=True')
    expect(source).toContain('"pending", required=True')
    expect(source).toContain('"management_expected_state_required" if required else None')
    expect(source).toContain('management_expected_broker_server_required')
    expect(source).toContain('management_expected_login_account_required')
    expect(source).toContain('params.get("confirm") is not True')
    expect(source).toContain('"message": "bridge_command_failed"')
    expect(source).not.toContain('{"status": "error", "message": str(e)}')
  })

  it('post-verifies generic pending cancellation and preserves uncertain outcomes', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('elif action == "cancel_pending":')
    const end = source.indexOf('elif action == "pending_list":', start)
    const block = source.slice(start, end)
    expect(start).toBeGreaterThan(0)
    expect(block).toContain('remaining = self.mt5.orders_get(ticket=ticket)')
    expect(block).toContain('"status": "uncertain"')
    expect(block).toContain('"status": "uncertain" if unresolved else "rejected"')
  })

  it('keeps executable auto-update disabled until signed manifests are implemented', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).not.toContain('class UpdateDownloader')
    expect(source).not.toContain('class UpdateDialog')
    expect(source).not.toContain('subprocess.Popen(')
    expect(source).not.toContain('os._exit(0)')
  })

  it('keeps a saved observer profile recoverable when its process fails to launch', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('def _schedule_observer_source_start_check(self, slug):')
    expect(source).toContain('def _verify_observer_source_started(self, slug):')
    expect(source).toContain('观摩源已保存但未启动')
    expect(source).toContain('档案和加密凭据已安全保存')
    expect(source).toContain('观摩源已保存但名称登记失败')
    expect(source).toContain('没有建立运行心跳')
  })

  it('uses cooperative worker shutdown without destroying a running QThread', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('self._stop_event = threading.Event()')
    expect(source).toContain('loop.call_soon_threadsafe(async_stop_event.set)')
    expect(source).toContain('await self._sleep_or_stop(retry_delay)')
    expect(source).toContain('with self._mt5_lock:')
    expect(source).not.toContain('self._worker.terminate()')
    expect(source).not.toContain('self._worker.wait(')
    expect(source).not.toContain('QTimer.singleShot(200, QApplication.quit)')
    const quitStart = source.indexOf('    def _do_quit(self):')
    const quitBlock = source.slice(quitStart, source.indexOf('    def closeEvent(', quitStart))
    expect(quitBlock.indexOf('self.tray.hide()')).toBeGreaterThan(
      quitBlock.indexOf('def _finish_quit_if_ready(self):'),
    )
  })

  it('protects every persisted Bridge credential with Windows DPAPI', () => {
    const gui = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const configStore = readFileSync(new URL('../public/ai/bridge_config_store.py', import.meta.url), 'utf8')
    const secrets = readFileSync(new URL('../public/ai/bridge_secret_store.py', import.meta.url), 'utf8')
    const profiles = readFileSync(new URL('../public/ai/bridge_profile_runtime.py', import.meta.url), 'utf8')
    expect(gui).toContain('_CONFIG_STORE = BridgeConfigStore(CONFIG_PATH)')
    expect(configStore).toContain('config_from_storage(stored)')
    expect(configStore).toContain('config_for_storage(config)')
    expect(configStore).toContain('self._lock = threading.RLock()')
    expect(configStore).toContain('tempfile.NamedTemporaryFile(')
    expect(gui).not.toContain('_ENC_KEY = "AURUM_BRIDGE_v2"')
    expect(secrets).toContain('crypt32.CryptProtectData.argtypes')
    expect(secrets).toContain('crypt32.CryptUnprotectData.argtypes')
    expect(secrets).toContain('kernel32.LocalFree.argtypes = [ctypes.c_void_p]')
    expect(secrets).toContain('SECRET_FIELDS = ("token", "refresh_token", "saved_password")')
    expect(profiles).toContain('_write_json_atomic(path, config_for_storage(config))')
  })

  it('exchanges the access token for a one-use websocket ticket', () => {
    const gui = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const server = readFileSync(new URL('../server/bridge-ws.js', import.meta.url), 'utf8')
    expect(gui).toContain('/api/auth/bridge-ticket')
    expect(gui).toContain('?type=bridge&ticket={encoded_ticket}')
    expect(gui).toContain('(r"(?i)([?&]ticket=)[^&\\s,;]+"')
    expect(gui).toContain('return _mask_log_text(value)')
    expect(gui).toContain('parts.append(BridgeWorker._short_text(msg, 200))')
    expect(gui).not.toContain('?type=bridge&token={self.token}')
    expect(server).toContain('consumeBridgeConnectionTicket(ticket)')
    expect(server).toContain('Invalid or expired bridge ticket')
    expect(server).toContain('pending.userId === Number(userId) && pending.ws === ws')
    expect(server).toContain('pending.bridgeGeneration === Number(bridge?.generation || 0)')
    expect(server).toContain('Bridge connection replaced before command result')
    expect(server).toContain('ws:bridge.ws, bridgeGeneration:Number(bridge.generation || 0)')
  })

  it('deduplicates execution commands before order_send and reconciles by exact MT5 identity', () => {
    const gui = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const lookup = readFileSync(new URL('../public/ai/bridge_order_idempotency.py', import.meta.url), 'utf8')
    const openStart = gui.indexOf('if action == "open":')
    const openSend = gui.indexOf('self.mt5.order_send(', openStart)
    const pendingStart = gui.indexOf('elif action == "pending":', openStart)
    const pendingSend = gui.indexOf('self.mt5.order_send(', pendingStart)
    expect(gui.indexOf('self._preflight_new_order(params, "trade")', openStart)).toBeLessThan(openSend)
    expect(gui.indexOf('self._preflight_new_order(params, "pending")', pendingStart)).toBeLessThan(pendingSend)
    expect(gui).toContain('if command_id and command_id in command_cache:')
    expect(gui).toContain('"message": "command_id_conflict"')
    expect(gui).toContain('while len(command_cache) > 500:')
    expect(gui).toContain('"message": "operation_id_conflict"')
    expect(gui).toContain('{"signature": operation_signature, "result": dict(result)}')
    expect(gui).toContain('return lookup_existing_execution(')
    expect(lookup).toContain('_text(actual) == expected_text')
    expect(lookup).not.toContain('command_ref in')
    expect(lookup).toContain('"complete": True')
    expect(lookup).toContain('history_orders_get(date_from, date_to)')
    expect(lookup).toContain('history_deals_get(date_from, date_to)')
    expect(gui).toContain('command_ref = self._normalize_order_comment(params.get("comment"), "")')
    expect(gui).toContain('"comment": self._normalize_order_comment(params.get("comment"), "AI交易实验室")')
    expect(gui).toContain('"comment": self._normalize_order_comment(params.get("comment"), "AI挂单")')
  })

  it('accepts HTTP and HTTPS bridge servers while preserving URL safety checks', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const httpClient = readFileSync(new URL('../public/ai/bridge_http_client.py', import.meta.url), 'utf8')
    expect(httpClient).toContain('parsed.scheme in {"http", "https"} and parsed.hostname')
    expect(httpClient).toContain('桥接服务器地址仅支持 HTTP 或 HTTPS')
    expect(httpClient).toContain('class SameOriginRedirectHandler')
    expect(httpClient).toContain('MAX_JSON_RESPONSE_BYTES = 2 * 1024 * 1024')
    expect(source).toContain('MAX_JSON_RESPONSE_BYTES, encode_json_body, validate_bridge_http_url,')
    expect(source).toContain('normalize_server_url, request_json,')
    expect(httpClient).toContain('def normalize_server_url(url):')
    expect(source).not.toContain('shell=True')
  })

  it('keeps GUI login and version checks off synchronous network calls', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const manualStart = source.indexOf('    def _do_login(self):')
    const manualLogin = source.slice(manualStart, source.indexOf('    def _finish_login(', manualStart))
    const autoStart = source.indexOf('    def _auto_login(self):')
    const autoLogin = source.slice(autoStart, source.indexOf('    def _on_login_success(', autoStart))
    const updateStart = source.indexOf('    def _check_update(self):')
    const updateCheck = source.slice(updateStart, source.indexOf('    def _version_newer(', updateStart))
    expect(manualLogin).toContain('AsyncJsonRequest(')
    expect(autoLogin).toContain('AsyncJsonRequest(')
    expect(updateCheck).toContain('AsyncJsonRequest(')
    expect(manualLogin).not.toContain('http_post_json(')
    expect(autoLogin).not.toContain('http_get_json(')
    expect(autoLogin).not.toContain('http_post_json(')
    expect(updateCheck).not.toContain('http_get_json(')
    expect(autoLogin).toContain('if not cfg.get("auto_login") or self.stack.currentIndex() != 0:')
    expect(autoLogin).toContain('cfg.pop("refresh_token", None)')
  })

  it('does not report login or settings persistence success when encrypted config writes fail', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('if not save_config(cfg):')
    expect(source).toContain('登录成功，但本机加密配置保存失败；桥接尚未启动')
    expect(source).toContain('server = normalize_server_url(server)')
    expect(source).toContain('"✅ 已保存" if saved else "❌ 本机配置保存失败"')
    const finishedStart = source.indexOf('def _on_worker_finished(self):')
    const finishedEnd = source.indexOf('def _reset_bridge_ui(self):', finishedStart)
    expect(source.slice(finishedStart, finishedEnd)).not.toContain('normalize_server_url(server)')
    const loginStart = source.indexOf('def _do_login(self):')
    const loginEnd = source.indexOf('# ══════════════════════════════════════════════════════════', loginStart)
    expect(source.slice(loginStart, loginEnd)).toContain('server = normalize_server_url(server)')
  })

  it('cannot restore credentials after the user logs out while a refresh is in flight', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    expect(source).toContain('if not self.running:\n            return False')
    const logoutStart = source.indexOf('    def _on_logout(self):')
    const logoutBlock = source.slice(logoutStart, source.indexOf('    def _init_tray(', logoutStart))
    expect(logoutBlock.indexOf('self.bridge_page.stop_bridge()')).toBeLessThan(
      logoutBlock.indexOf('self.settings_page._clear_local_auth()'),
    )
  })

  it('keeps legacy auto-update disabled while exposing the configured signed installer release', () => {
    const source = readFileSync(new URL('../server/routes/ai/index.js', import.meta.url), 'utf8')
    expect(readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim()).toBe('3.0.0')
    expect(source).toContain('auto_update_enabled: BRIDGE_RELEASE.v3')
    expect(source).toContain("updater_url: ''")
    expect(source).toContain("BRIDGE_RELEASE.v3 ? null : 'signed_update_manifest_required'")
    expect(source).toContain("BRIDGE_RELEASE.v3 ? 'signed_manifest_v2' : 'legacy_manual_installer'")
    expect(source).toContain('const BRIDGE_RELEASE = resolveBridgeInstallerRelease()')
    expect(source).toContain('full_url: BRIDGE_RELEASE.fullUrl')
    expect(source).toContain('file_size: BRIDGE_RELEASE.fileSize')
    expect(source).toContain('sha256: BRIDGE_RELEASE.sha256')
  })

  it('exposes lightweight symbol metadata for account simulation without exporting history', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('elif action == "symbol_snapshot":')
    const end = source.indexOf('elif action == "order_lookup":', start)
    const block = source.slice(start, end)
    expect(block).toContain('self.mt5.symbol_info(symbol)')
    expect(block).toContain('"tick_value":')
    expect(block).toContain('"contract_size":')
    expect(block).toContain('"margin_initial":')
    expect(block).toContain('"margin_maintenance":')
    expect(block).toContain('self.mt5.order_calc_margin')
    expect(block).toContain('"margin_per_lot_buy":')
    expect(block).toContain('"margin_per_lot_sell":')
    expect(block).toContain('"margin_reference_price_buy":')
    expect(block).toContain('"margin_reference_price_sell":')
    expect(block).toContain('"margin_profile_currency":')
    expect(block).toContain('"margin_profile_volume":')
    expect(block).toContain('"trade_stops_level":')
    expect(block).toContain('"trade_freeze_level":')
    expect(block).toContain('"volume_limit":')
    expect(block).toContain('"swap_mode":')
    expect(block).toContain('"swap_rollover3days":')
    expect(block).toContain('"swap_long":')
    expect(block).toContain('"swap_short":')
    expect(block).toContain('"swap_sunday":')
    expect(block).toContain('"swap_wednesday":')
    expect(block).toContain('"swap_saturday":')
    expect(block).toContain('"currency_base":')
    expect(block).toContain('"currency_margin":')
    expect(block).toContain('"leverage":')
    expect(block).toContain('"margin_mode":')
    expect(block).toContain('"margin_so_mode":')
    expect(block).toContain('"margin_so_so":')
    expect(block).not.toContain('history_deals_get')
    expect(block).not.toContain('positions_get')
    expect(block).not.toContain('orders_get')
  })

  it('aggregates bounded daily account performance inside the bridge', () => {
    const source = readFileSync(new URL('../public/ai/aurum_bridge_gui.py', import.meta.url), 'utf8')
    const start = source.indexOf('def _performance_daily(self, params):')
    const end = source.indexOf('\n    def ', start + 10)
    const block = source.slice(start, end)
    expect(source).toContain('elif action == "performance_daily":')
    expect(block).toContain('history_deals_get')
    expect(block).toContain('performance date range exceeds 31 days')
    expect(block).toContain('"realized_net"')
    expect(block).toContain('"source_hash"')
    expect(block).not.toContain('"deals":')
  })
})
