import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const accountHtml = readFileSync(new URL('../public/account/index.html', import.meta.url), 'utf8')
const accountApp = readFileSync(new URL('../public/account/app.js', import.meta.url), 'utf8')
const accountCss = readFileSync(new URL('../public/account/styles.css', import.meta.url), 'utf8')
const aiHtml = readFileSync(new URL('../public/ai/index.html', import.meta.url), 'utf8')
const aiApp = readFileSync(new URL('../public/ai/app.js', import.meta.url), 'utf8')
const aiCss = readFileSync(new URL('../public/ai/styles.css', import.meta.url), 'utf8')
const aiResponsiveCss = readFileSync(new URL('../public/ai/responsive.css', import.meta.url), 'utf8')

describe('通知中心与 AI 实验室前端契约', () => {
  it('renders a hidden 1-99/99+ account badge and fixed non-flow important banner', () => {
    expect(aiHtml).toContain('id="notificationBadge"')
    expect(aiHtml).toContain('id="notificationBanner"')
    expect(aiHtml).toContain('role="status" aria-live="polite"')
    expect(aiCss).toMatch(/\.notification-banner\s*\{[\s\S]*?position:\s*fixed;/)
    expect(aiCss).toContain('.notification-banner[hidden] { display: none !important; }')
    expect(aiCss).toContain('.notification-badge[hidden] { display: none !important; }')
    expect(aiCss).toContain('background: var(--color-info, #6baee8)')
    expect(aiCss).toContain('max-height: 96px')
    expect(aiResponsiveCss).toContain('.notification-banner')
    expect(aiResponsiveCss).toContain('max-height: 58px')
    expect(aiResponsiveCss).toContain('@media (min-width: 761px) and (max-width: 1023px)')
    expect(aiResponsiveCss).toContain('width: min(520px, calc(100vw - 32px));')
    expect(aiResponsiveCss).toContain('top: 112px;')
    expect(aiResponsiveCss).toContain('body.ai-observer-mode .notification-banner')
    expect(aiResponsiveCss).toContain('top: 176px;')
    expect(aiApp).toContain('count >= 100 ? "99+"')
    expect(aiApp).toContain('账户中心，${count >= 100 ? "99+" : count} 条未读通知')
  })

  it('refreshes summary at startup, visibility, notification_created, and websocket reconnect without polling', () => {
    expect(aiApp).toContain('api("/api/notifications/summary")')
    expect(aiApp).toContain('document.addEventListener("visibilitychange"')
    expect(aiApp).toContain('if (msg.type === \'notification_created\')')
    expect(aiApp).toContain('state.notificationWsReady')
    expect(aiApp).toContain('if (wasNotificationWsReady) void refreshNotificationSummary()')
    expect(aiApp).not.toMatch(/setInterval\([^\n]*notifications\/summary/)
  })

  it('keeps account notification state separate for read and acknowledgement', () => {
    expect(accountApp).toContain("api('/api/notifications?limit=50')")
    expect(accountApp).toContain("api('/api/notifications/summary')")
    expect(accountApp).toContain("document.addEventListener('visibilitychange'")
    expect(accountApp).toContain('method:\'PATCH\',body:{ id }')
    expect(accountApp).toContain('`/api/notifications/${encodeURIComponent(id)}/acknowledge`')
    expect(accountApp).toContain('全部消息已标为已读')
    expect(accountApp).toContain('我知道了')
    expect(accountApp).toContain('notificationImportantUnacknowledgedCount')
    expect(accountApp).toContain('item.acknowledgedAt')
    expect(accountApp).toContain('item.isRead = true')
    expect(accountCss).toContain('.notification-item.is-important')
    expect(accountCss).toContain('body.account-main-embedded:not(.account-main-dark) .notification-item.is-unread .notification-item-heading strong')
    expect(accountCss).toContain('body.account-main-embedded:not(.account-main-dark) .notification-priority.important')
    expect(accountCss).toContain('body.account-main-embedded:not(.account-main-dark) .notification-status.warning')
  })

  it('only renders allowlisted same-origin relative notification links', () => {
    expect(accountApp).toContain("raw.startsWith('//')")
    expect(accountApp).toContain("pathname.startsWith('/admin')")
    expect(accountApp).toContain("pathname.startsWith('/api')")
    expect(accountApp).toContain("pathname.startsWith('/account/')")
    expect(accountApp).toContain("pathname.startsWith('/ai/')")
    expect(accountApp).toContain('event.preventDefault()')
  })

  it('uses origin and source checks and sends only the notification summary cross-window', () => {
    expect(accountApp).toContain('event.origin!==location.origin || event.source!==window.parent')
    expect(aiApp).toContain('event.origin !== window.location.origin || event.source !== $("accountCenterFrame")?.contentWindow')
    expect(accountApp).toContain("notifyParent('account-notifications-updated',notificationSummaryPayload())")
    const payloadStart = accountApp.indexOf('function notificationSummaryPayload()')
    const payloadEnd = accountApp.indexOf('function syncNotificationSummary', payloadStart)
    expect(payloadStart).toBeGreaterThan(-1)
    expect(accountApp.slice(payloadStart, payloadEnd)).not.toContain('message:')
    expect(aiApp).toContain('window.location.origin')
    expect(aiApp).toContain('notificationId')
  })
})
