-- M1 stable economic-calendar identity and immutable provider revisions.
-- TARGET: empty V4 side-by-side database after 20260905_016. Never run against the legacy source database.
-- Events without a provider-stable ID remain ingestion evidence and are not promoted; never synthesize identity from title/time.

CREATE TABLE IF NOT EXISTS economic_calendar_events (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  provider_event_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  country_code CHAR(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  country_name VARCHAR(191) NOT NULL,
  currency_code CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NULL,
  title VARCHAR(500) NOT NULL,
  scheduled_at_utc DATETIME(3) NOT NULL,
  time_precision ENUM('exact','date_only','tentative') NOT NULL,
  importance ENUM('low','medium','high','unknown') NOT NULL DEFAULT 'unknown',
  period_label VARCHAR(128) NULL,
  unit VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('scheduled','released','revised','delayed','cancelled') NOT NULL DEFAULT 'scheduled',
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  provider_updated_at_utc DATETIME(3) NULL,
  created_at_utc DATETIME(3) NOT NULL,
  updated_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_economic_calendar_provider_event (source_id, provider_event_id),
  KEY idx_economic_calendar_schedule (scheduled_at_utc, id),
  KEY idx_economic_calendar_filter (importance, country_code, scheduled_at_utc, id),
  CONSTRAINT fk_economic_calendar_source FOREIGN KEY (source_id) REFERENCES macro_data_sources (id),
  CONSTRAINT chk_economic_calendar_provider_id CHECK (provider_event_id IS NULL OR CHAR_LENGTH(provider_event_id)>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS economic_calendar_event_revisions (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  revision_number INT UNSIGNED NOT NULL,
  provider_revision_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('scheduled','released','revised','delayed','cancelled') NOT NULL,
  scheduled_at_utc DATETIME(3) NOT NULL,
  previous_value DECIMAL(30,10) NULL,
  consensus_value DECIMAL(30,10) NULL,
  actual_value DECIMAL(30,10) NULL,
  revised_previous_value DECIMAL(30,10) NULL,
  display_previous VARCHAR(128) NULL,
  display_consensus VARCHAR(128) NULL,
  display_actual VARCHAR(128) NULL,
  display_revised_previous VARCHAR(128) NULL,
  provider_updated_at_utc DATETIME(3) NULL,
  available_at_utc DATETIME(3) NOT NULL,
  ingested_at_utc DATETIME(3) NOT NULL,
  availability_confidence ENUM('exact','provider_date','retrieval_only','unknown') NOT NULL,
  content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  evidence_ref VARCHAR(2048) NULL,
  ingestion_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_economic_calendar_revision (event_id, revision_number),
  UNIQUE KEY uk_economic_calendar_provider_revision (event_id, provider_revision_key, content_sha256),
  UNIQUE KEY uk_economic_calendar_revision_content (event_id, content_sha256),
  KEY idx_economic_calendar_available (event_id, available_at_utc, id),
  KEY idx_economic_calendar_ingestion (ingestion_run_id, id),
  CONSTRAINT fk_economic_calendar_revision_event FOREIGN KEY (event_id) REFERENCES economic_calendar_events (id),
  CONSTRAINT fk_economic_calendar_revision_ingestion FOREIGN KEY (ingestion_run_id) REFERENCES macro_ingestion_runs (id),
  CONSTRAINT chk_economic_calendar_revision_number CHECK (revision_number>0),
  CONSTRAINT chk_economic_calendar_provider_revision CHECK (provider_revision_key IS NULL OR CHAR_LENGTH(provider_revision_key)>0),
  CONSTRAINT chk_economic_calendar_availability CHECK (available_at_utc<=ingested_at_utc OR availability_confidence IN ('retrieval_only','unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
