-- M1 macro source registry, immutable observations and ingestion evidence.
-- TARGET: empty V4 side-by-side database after 20260904_014. Never run against the legacy source database.
-- Run scripts/verify-v4-migration-target.mjs first. This migration performs no external I/O and no legacy backfill.

CREATE TABLE IF NOT EXISTS macro_data_sources (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  display_name VARCHAR(191) NOT NULL,
  status ENUM('candidate','trial','legal_review','approved','suspended','retired') NOT NULL DEFAULT 'candidate',
  credential_ref VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  terms_uri VARCHAR(2048) NULL,
  terms_version VARCHAR(128) NULL,
  attribution_text VARCHAR(2000) NULL,
  display_allowed TINYINT(1) NOT NULL DEFAULT 0,
  cache_allowed TINYINT(1) NOT NULL DEFAULT 0,
  retention_allowed TINYINT(1) NOT NULL DEFAULT 0,
  modeling_allowed TINYINT(1) NOT NULL DEFAULT 0,
  derived_data_allowed TINYINT(1) NOT NULL DEFAULT 0,
  license_reviewed_at_utc DATETIME(3) NULL,
  license_expires_at_utc DATETIME(3) NULL,
  rate_limit_json JSON NOT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_user_id INT NOT NULL,
  created_at_utc DATETIME(3) NOT NULL,
  updated_at_utc DATETIME(3) NOT NULL,
  retired_at_utc DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_macro_data_sources_key (source_key),
  KEY idx_macro_data_sources_status (status, id),
  CONSTRAINT fk_macro_data_sources_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id),
  CONSTRAINT chk_macro_source_approved_rights CHECK (
    status<>'approved' OR (license_reviewed_at_utc IS NOT NULL AND cache_allowed=1 AND retention_allowed=1)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS macro_series (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_id BIGINT UNSIGNED NOT NULL,
  series_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_series_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  display_name VARCHAR(191) NOT NULL,
  series_kind ENUM('factor','gold_benchmark','volatility','geopolitical_risk') NOT NULL,
  value_kind ENUM('decimal','text') NOT NULL DEFAULT 'decimal',
  unit VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  frequency ENUM('intraday','daily','weekly','monthly','irregular') NOT NULL,
  freshness_calendar VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  freshness_limit_seconds INT UNSIGNED NOT NULL,
  gold_relation_rule_json JSON NOT NULL,
  status ENUM('enabled','disabled','retired') NOT NULL DEFAULT 'disabled',
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at_utc DATETIME(3) NOT NULL,
  updated_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_macro_series_code (series_code),
  UNIQUE KEY uk_macro_series_provider_key (source_id, provider_series_key),
  KEY idx_macro_series_source_status (source_id, status, id),
  CONSTRAINT fk_macro_series_source FOREIGN KEY (source_id) REFERENCES macro_data_sources (id),
  CONSTRAINT chk_macro_series_freshness CHECK (freshness_limit_seconds BETWEEN 60 AND 31536000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS macro_ingestion_runs (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  series_id BIGINT UNSIGNED NULL,
  idempotency_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  requested_from_utc DATETIME(3) NULL,
  requested_to_utc DATETIME(3) NULL,
  status ENUM('queued','running','succeeded','failed','status_unknown','cancelled') NOT NULL,
  lease_owner VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_expires_at_utc DATETIME(3) NULL,
  fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
  request_started_at_utc DATETIME(3) NULL,
  response_received_at_utc DATETIME(3) NULL,
  response_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  evidence_ref VARCHAR(2048) NULL,
  parser_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  inserted_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_summary VARCHAR(1000) NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at_utc DATETIME(3) NOT NULL,
  updated_at_utc DATETIME(3) NOT NULL,
  completed_at_utc DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_macro_ingestion_idempotency (source_id, idempotency_key),
  KEY idx_macro_ingestion_claim (status, lease_expires_at_utc, created_at_utc, id),
  KEY idx_macro_ingestion_series (series_id, created_at_utc, id),
  CONSTRAINT fk_macro_ingestion_source FOREIGN KEY (source_id) REFERENCES macro_data_sources (id),
  CONSTRAINT fk_macro_ingestion_series FOREIGN KEY (series_id) REFERENCES macro_series (id),
  CONSTRAINT chk_macro_ingestion_window CHECK (requested_from_utc IS NULL OR requested_to_utc IS NULL OR requested_to_utc>=requested_from_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS macro_observations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  series_id BIGINT UNSIGNED NOT NULL,
  ingestion_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  observation_at_utc DATETIME(3) NOT NULL,
  available_at_utc DATETIME(3) NOT NULL,
  ingested_at_utc DATETIME(3) NOT NULL,
  provider_updated_at_utc DATETIME(3) NULL,
  provider_vintage_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  availability_confidence ENUM('exact','provider_date','retrieval_only','unknown') NOT NULL,
  decimal_value DECIMAL(30,10) NULL,
  text_value VARCHAR(2000) NULL,
  content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  evidence_ref VARCHAR(2048) NULL,
  parser_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_macro_observation_version (series_id, observation_at_utc, available_at_utc, content_sha256),
  KEY idx_macro_observations_point_in_time (series_id, available_at_utc, observation_at_utc, id),
  KEY idx_macro_observations_ingestion (ingestion_run_id, id),
  CONSTRAINT fk_macro_observation_series FOREIGN KEY (series_id) REFERENCES macro_series (id),
  CONSTRAINT fk_macro_observation_ingestion FOREIGN KEY (ingestion_run_id) REFERENCES macro_ingestion_runs (id),
  CONSTRAINT chk_macro_observation_value CHECK ((decimal_value IS NULL)<>(text_value IS NULL)),
  CONSTRAINT chk_macro_observation_availability CHECK (available_at_utc<=ingested_at_utc OR availability_confidence IN ('retrieval_only','unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
