CREATE TABLE `strategy_subscriptions_v4_build` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned NOT NULL,
  `standard_symbol` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `analysis_strategy_id` bigint unsigned NOT NULL,
  `analysis_strategy_version_id` bigint unsigned NOT NULL,
  `trader_strategy_id` bigint unsigned DEFAULT NULL,
  `trader_strategy_version_id` bigint unsigned DEFAULT NULL,
  `analysis_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `trader_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `trade_send_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `status` enum('active','paused','ended') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `active_execution_key` varchar(255) CHARACTER SET ascii COLLATE ascii_bin GENERATED ALWAYS AS ((case when ((`status` = _utf8mb4'active') and (`trader_enabled` = 1)) then concat(cast(`trading_account_id` as char charset utf8mb4),_utf8mb4':',convert(`standard_symbol` using utf8mb4)) else NULL end)) STORED,
  `legacy_source_table` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `legacy_id` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_strategy_subscription_identity` (`user_id`,`trading_account_id`,`analysis_strategy_id`,`standard_symbol`),
  UNIQUE KEY `uk_strategy_subscription_execution_slot` (`active_execution_key`),
  UNIQUE KEY `uk_strategy_subscription_legacy` (`legacy_source_table`,`legacy_id`),
  KEY `idx_strategy_subscriptions_analysis` (`user_id`,`analysis_strategy_version_id`,`standard_symbol`,`status`,`id`),
  KEY `idx_strategy_subscriptions_account` (`trading_account_id`,`status`,`id`),
  KEY `fk_strategy_subscriptions_analysis` (`analysis_strategy_id`),
  KEY `fk_strategy_subscriptions_analysis_version` (`analysis_strategy_version_id`,`analysis_strategy_id`),
  KEY `fk_strategy_subscriptions_trader` (`trader_strategy_id`),
  KEY `fk_strategy_subscriptions_trader_version` (`trader_strategy_version_id`,`trader_strategy_id`),
  CONSTRAINT `build_sub_725f39a146e86dec96dbd0aa` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts_v4_build` (`id`),
  CONSTRAINT `build_sub_7a251248c43ab0574975e1a3` FOREIGN KEY (`analysis_strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_sub_0c51ad8469fff6ff093c86f9` FOREIGN KEY (`analysis_strategy_version_id`, `analysis_strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_sub_4fc8ff10102c070027098b11` FOREIGN KEY (`trader_strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_sub_b279ce344487dfeef755f66f` FOREIGN KEY (`trader_strategy_version_id`, `trader_strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_sub_9294d57ac7727ef83f7993ac` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `build_sub_2be294fb98c34a07474f83ee` CHECK (((`trade_send_enabled` = 0) or (`trader_enabled` = 1))),
  CONSTRAINT `build_sub_cb36259f8d93625320fd92a1` CHECK ((((`trader_enabled` = 0) and (`trade_send_enabled` = 0)) or ((`trader_enabled` = 1) and (`trader_strategy_id` is not null) and (`trader_strategy_version_id` is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `subscription_schedules_v4_build` (
  `subscription_id` bigint unsigned NOT NULL,
  `cadence_seconds` int unsigned NOT NULL DEFAULT '300',
  `receive_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `receive_window_json` json NOT NULL,
  `next_due_at_utc` datetime(3) DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `updated_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`subscription_id`),
  KEY `idx_subscription_schedules_due` (`next_due_at_utc`,`subscription_id`),
  CONSTRAINT `build_sub_2b06c113d0f260d265749d3a` FOREIGN KEY (`subscription_id`) REFERENCES `strategy_subscriptions_v4_build` (`id`),
  CONSTRAINT `build_sub_51e6c8f8dfde6e942b999fd8` CHECK ((`cadence_seconds` >= 60))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `subscription_execution_preferences_v4_build` (
  `subscription_id` bigint unsigned NOT NULL,
  `contract_version` smallint unsigned NOT NULL,
  `take_profit_mode` enum('ai_recommended','conservative','standard','trend') COLLATE utf8mb4_unicode_ci NOT NULL,
  `revision` bigint unsigned NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`subscription_id`),
  CONSTRAINT `build_sub_da412482d076c3afdd229ef8` FOREIGN KEY (`subscription_id`) REFERENCES `strategy_subscriptions_v4_build` (`id`),
  CONSTRAINT `build_sub_25781eaa43f7b071cd986a08` CHECK ((`revision` > 0)),
  CONSTRAINT `build_sub_272b3f339f2798e19fd95c19` CHECK ((`contract_version` = 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
