-- Final observed macro definitions. Additive same-database phase; no business data initialization.

CREATE TABLE `macro_data_sources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `source_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `display_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('candidate','trial','legal_review','approved','suspended','retired') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'candidate',
  `credential_ref` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `terms_uri` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terms_version` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attribution_text` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `cache_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `retention_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `modeling_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `derived_data_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `license_reviewed_at_utc` datetime(3) DEFAULT NULL,
  `license_expires_at_utc` datetime(3) DEFAULT NULL,
  `rate_limit_json` json NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_by_user_id` int NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `retired_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_data_sources_key` (`source_key`),
  KEY `idx_macro_data_sources_status` (`status`,`id`),
  KEY `fk_macro_data_sources_creator` (`created_by_user_id`),
  CONSTRAINT `fk_macro_data_sources_creator` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_macro_source_approved_rights` CHECK (((`status` <> _utf8mb4'approved') or ((`license_reviewed_at_utc` is not null) and (`cache_allowed` = 1) and (`retention_allowed` = 1))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_feature_sets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `feature_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `version_number` int unsigned NOT NULL,
  `schema_version` smallint unsigned NOT NULL,
  `definition_json` json NOT NULL,
  `definition_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` enum('draft','active','retired') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `created_by_user_id` int NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `activated_at_utc` datetime(3) DEFAULT NULL,
  `retired_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_feature_set_version` (`feature_key`,`version_number`),
  KEY `idx_macro_feature_set_status` (`status`,`id`),
  KEY `fk_macro_feature_set_creator` (`created_by_user_id`),
  CONSTRAINT `fk_macro_feature_set_creator` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_macro_feature_set_version` CHECK (((`version_number` > 0) and (`schema_version` > 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `economic_calendar_events` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_id` bigint unsigned NOT NULL,
  `provider_event_id` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `country_code` char(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `country_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `currency_code` char(3) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `title` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scheduled_at_utc` datetime(3) NOT NULL,
  `time_precision` enum('exact','date_only','tentative') COLLATE utf8mb4_unicode_ci NOT NULL,
  `importance` enum('low','medium','high','unknown') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unknown',
  `period_label` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `status` enum('scheduled','released','revised','delayed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'scheduled',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `provider_updated_at_utc` datetime(3) DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_economic_calendar_provider_event` (`source_id`,`provider_event_id`),
  KEY `idx_economic_calendar_schedule` (`scheduled_at_utc`,`id`),
  KEY `idx_economic_calendar_filter` (`importance`,`country_code`,`scheduled_at_utc`,`id`),
  CONSTRAINT `fk_economic_calendar_source` FOREIGN KEY (`source_id`) REFERENCES `macro_data_sources` (`id`),
  CONSTRAINT `chk_economic_calendar_provider_id` CHECK (((`provider_event_id` is null) or (char_length(`provider_event_id`) > 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_model_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `model_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `version_number` int unsigned NOT NULL,
  `feature_set_id` bigint unsigned NOT NULL,
  `model_kind` enum('baseline','linear','elastic_net','xgboost','regime') COLLATE utf8mb4_unicode_ci NOT NULL,
  `lifecycle_status` enum('draft','evaluating','shadow','active','rejected','retired') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `training_cutoff_at_utc` datetime(3) NOT NULL,
  `config_json` json NOT NULL,
  `input_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `artifact_ref` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL,
  `artifact_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `report_ref` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL,
  `report_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_by_user_id` int NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `activated_at_utc` datetime(3) DEFAULT NULL,
  `retired_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_model_version` (`model_key`,`version_number`),
  KEY `idx_macro_model_lifecycle` (`lifecycle_status`,`id`),
  KEY `fk_macro_model_feature_set` (`feature_set_id`),
  KEY `fk_macro_model_creator` (`created_by_user_id`),
  CONSTRAINT `fk_macro_model_creator` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_macro_model_feature_set` FOREIGN KEY (`feature_set_id`) REFERENCES `macro_feature_sets` (`id`),
  CONSTRAINT `chk_macro_model_version` CHECK ((`version_number` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_series` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `source_id` bigint unsigned NOT NULL,
  `series_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider_series_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `display_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `series_kind` enum('factor','gold_benchmark','volatility','geopolitical_risk') COLLATE utf8mb4_unicode_ci NOT NULL,
  `value_kind` enum('decimal','text') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'decimal',
  `unit` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `frequency` enum('intraday','daily','weekly','monthly','irregular') COLLATE utf8mb4_unicode_ci NOT NULL,
  `freshness_calendar` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `freshness_limit_seconds` int unsigned NOT NULL,
  `gold_relation_rule_json` json NOT NULL,
  `status` enum('enabled','disabled','retired') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'disabled',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_series_code` (`series_code`),
  UNIQUE KEY `uk_macro_series_provider_key` (`source_id`,`provider_series_key`),
  KEY `idx_macro_series_source_status` (`source_id`,`status`,`id`),
  CONSTRAINT `fk_macro_series_source` FOREIGN KEY (`source_id`) REFERENCES `macro_data_sources` (`id`),
  CONSTRAINT `chk_macro_series_freshness` CHECK ((`freshness_limit_seconds` between 60 and 31536000))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_ingestion_runs` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_id` bigint unsigned NOT NULL,
  `series_id` bigint unsigned DEFAULT NULL,
  `idempotency_key` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `requested_from_utc` datetime(3) DEFAULT NULL,
  `requested_to_utc` datetime(3) DEFAULT NULL,
  `status` enum('queued','running','succeeded','failed','status_unknown','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL,
  `lease_owner` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `lease_expires_at_utc` datetime(3) DEFAULT NULL,
  `fencing_token` bigint unsigned NOT NULL DEFAULT '0',
  `request_started_at_utc` datetime(3) DEFAULT NULL,
  `response_received_at_utc` datetime(3) DEFAULT NULL,
  `response_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `evidence_ref` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parser_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `inserted_count` int unsigned NOT NULL DEFAULT '0',
  `skipped_count` int unsigned NOT NULL DEFAULT '0',
  `error_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_summary` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_ingestion_idempotency` (`source_id`,`idempotency_key`),
  KEY `idx_macro_ingestion_claim` (`status`,`lease_expires_at_utc`,`created_at_utc`,`id`),
  KEY `idx_macro_ingestion_series` (`series_id`,`created_at_utc`,`id`),
  CONSTRAINT `fk_macro_ingestion_series` FOREIGN KEY (`series_id`) REFERENCES `macro_series` (`id`),
  CONSTRAINT `fk_macro_ingestion_source` FOREIGN KEY (`source_id`) REFERENCES `macro_data_sources` (`id`),
  CONSTRAINT `chk_macro_ingestion_window` CHECK (((`requested_from_utc` is null) or (`requested_to_utc` is null) or (`requested_to_utc` >= `requested_from_utc`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_pipeline_jobs` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `job_kind` enum('feature_build','model_train','model_evaluate','snapshot_publish','health_refresh') COLLATE utf8mb4_unicode_ci NOT NULL,
  `idempotency_key` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `feature_set_id` bigint unsigned DEFAULT NULL,
  `model_version_id` bigint unsigned DEFAULT NULL,
  `data_cutoff_at_utc` datetime(3) DEFAULT NULL,
  `input_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `status` enum('queued','running','succeeded','failed','status_unknown','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL,
  `lease_owner` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `lease_expires_at_utc` datetime(3) DEFAULT NULL,
  `fencing_token` bigint unsigned NOT NULL DEFAULT '0',
  `error_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_summary` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result_ref` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `requested_by_user_id` int DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_pipeline_job_idempotency` (`job_kind`,`idempotency_key`),
  KEY `idx_macro_pipeline_job_claim` (`status`,`lease_expires_at_utc`,`created_at_utc`,`id`),
  KEY `fk_macro_pipeline_feature_set` (`feature_set_id`),
  KEY `fk_macro_pipeline_model` (`model_version_id`),
  KEY `fk_macro_pipeline_requester` (`requested_by_user_id`),
  CONSTRAINT `fk_macro_pipeline_feature_set` FOREIGN KEY (`feature_set_id`) REFERENCES `macro_feature_sets` (`id`),
  CONSTRAINT `fk_macro_pipeline_model` FOREIGN KEY (`model_version_id`) REFERENCES `macro_model_versions` (`id`),
  CONSTRAINT `fk_macro_pipeline_requester` FOREIGN KEY (`requested_by_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_research_snapshots` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `schema_version` smallint unsigned NOT NULL DEFAULT '0',
  `business_date` date DEFAULT NULL,
  `data_cutoff_at_utc` datetime(3) DEFAULT NULL,
  `feature_set_id` bigint unsigned DEFAULT NULL,
  `model_version_id` bigint unsigned DEFAULT NULL,
  `owner_scope` enum('platform','user') COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner_user_id` int DEFAULT NULL,
  `revision` bigint unsigned NOT NULL,
  `publication_status` enum('legacy','draft','published','superseded','invalidated') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'legacy',
  `freshness_status` enum('fresh','stale','partial','unavailable') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unavailable',
  `health_status` enum('healthy','degraded','failed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'failed',
  `horizon` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `observed_at_utc` datetime(3) NOT NULL,
  `valid_until_utc` datetime(3) NOT NULL,
  `published_at_utc` datetime(3) DEFAULT NULL,
  `superseded_at_utc` datetime(3) DEFAULT NULL,
  `content_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_json` json NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `active_publication_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin GENERATED ALWAYS AS ((case when ((`publication_status` = _utf8mb4'published') and (`superseded_at_utc` is null)) then concat(convert(coalesce(`horizon`,_ascii'') using utf8mb4),_utf8mb4':',coalesce(cast(`business_date` as char charset utf8mb4),_utf8mb4'')) else NULL end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_snapshot_active_publication` (`active_publication_key`),
  KEY `idx_macro_snapshot_user` (`owner_user_id`,`valid_until_utc`,`observed_at_utc`,`id`),
  KEY `idx_macro_snapshot_platform` (`owner_scope`,`valid_until_utc`,`observed_at_utc`,`id`),
  KEY `idx_macro_snapshot_latest` (`publication_status`,`published_at_utc`,`id`),
  KEY `idx_macro_snapshot_feature` (`feature_set_id`,`data_cutoff_at_utc`,`id`),
  KEY `fk_macro_snapshot_model` (`model_version_id`),
  CONSTRAINT `fk_macro_snapshot_feature` FOREIGN KEY (`feature_set_id`) REFERENCES `macro_feature_sets` (`id`),
  CONSTRAINT `fk_macro_snapshot_model` FOREIGN KEY (`model_version_id`) REFERENCES `macro_model_versions` (`id`),
  CONSTRAINT `fk_macro_snapshot_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_macro_snapshot_owner` CHECK ((((`owner_scope` = _utf8mb4'platform') and (`owner_user_id` is null)) or ((`owner_scope` = _utf8mb4'user') and (`owner_user_id` is not null)))),
  CONSTRAINT `chk_macro_snapshot_platform_v1` CHECK (((`schema_version` = 0) or ((`owner_scope` = _utf8mb4'platform') and (`owner_user_id` is null)))),
  CONSTRAINT `chk_macro_snapshot_publication` CHECK (((`publication_status` in (_utf8mb4'legacy',_utf8mb4'draft')) or ((`schema_version` > 0) and (`business_date` is not null) and (`data_cutoff_at_utc` is not null) and (`feature_set_id` is not null) and (`horizon` is not null) and (`published_at_utc` is not null)))),
  CONSTRAINT `chk_macro_snapshot_superseded` CHECK ((((`publication_status` = _utf8mb4'superseded') and (`superseded_at_utc` is not null)) or (`publication_status` <> _utf8mb4'superseded'))),
  CONSTRAINT `chk_macro_snapshot_timing` CHECK (((`schema_version` = 0) or (`publication_status` in (_utf8mb4'legacy',_utf8mb4'draft')) or ((`data_cutoff_at_utc` <= `published_at_utc`) and (`published_at_utc` < `valid_until_utc`)))),
  CONSTRAINT `chk_macro_snapshot_validity` CHECK ((`valid_until_utc` > `observed_at_utc`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `economic_calendar_event_revisions` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `event_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `revision_number` int unsigned NOT NULL,
  `provider_revision_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `status` enum('scheduled','released','revised','delayed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL,
  `scheduled_at_utc` datetime(3) NOT NULL,
  `previous_value` decimal(30,10) DEFAULT NULL,
  `consensus_value` decimal(30,10) DEFAULT NULL,
  `actual_value` decimal(30,10) DEFAULT NULL,
  `revised_previous_value` decimal(30,10) DEFAULT NULL,
  `display_previous` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_consensus` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_actual` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_revised_previous` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_updated_at_utc` datetime(3) DEFAULT NULL,
  `available_at_utc` datetime(3) NOT NULL,
  `ingested_at_utc` datetime(3) NOT NULL,
  `availability_confidence` enum('exact','provider_date','retrieval_only','unknown') COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `evidence_ref` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ingestion_run_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_economic_calendar_revision` (`event_id`,`revision_number`),
  UNIQUE KEY `uk_economic_calendar_revision_content` (`event_id`,`content_sha256`),
  UNIQUE KEY `uk_economic_calendar_provider_revision` (`event_id`,`provider_revision_key`,`content_sha256`),
  KEY `idx_economic_calendar_available` (`event_id`,`available_at_utc`,`id`),
  KEY `idx_economic_calendar_ingestion` (`ingestion_run_id`,`id`),
  CONSTRAINT `fk_economic_calendar_revision_event` FOREIGN KEY (`event_id`) REFERENCES `economic_calendar_events` (`id`),
  CONSTRAINT `fk_economic_calendar_revision_ingestion` FOREIGN KEY (`ingestion_run_id`) REFERENCES `macro_ingestion_runs` (`id`),
  CONSTRAINT `chk_economic_calendar_availability` CHECK (((`available_at_utc` <= `ingested_at_utc`) or (`availability_confidence` in (_utf8mb4'retrieval_only',_utf8mb4'unknown')))),
  CONSTRAINT `chk_economic_calendar_provider_revision` CHECK (((`provider_revision_key` is null) or (char_length(`provider_revision_key`) > 0))),
  CONSTRAINT `chk_economic_calendar_revision_number` CHECK ((`revision_number` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_observations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `series_id` bigint unsigned NOT NULL,
  `ingestion_run_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `observation_at_utc` datetime(3) NOT NULL,
  `available_at_utc` datetime(3) NOT NULL,
  `ingested_at_utc` datetime(3) NOT NULL,
  `provider_updated_at_utc` datetime(3) DEFAULT NULL,
  `provider_vintage_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `availability_confidence` enum('exact','provider_date','retrieval_only','unknown') COLLATE utf8mb4_unicode_ci NOT NULL,
  `decimal_value` decimal(30,10) DEFAULT NULL,
  `text_value` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `evidence_ref` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parser_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_macro_observation_version` (`series_id`,`observation_at_utc`,`available_at_utc`,`content_sha256`),
  KEY `idx_macro_observations_point_in_time` (`series_id`,`available_at_utc`,`observation_at_utc`,`id`),
  KEY `idx_macro_observations_ingestion` (`ingestion_run_id`,`id`),
  CONSTRAINT `fk_macro_observation_ingestion` FOREIGN KEY (`ingestion_run_id`) REFERENCES `macro_ingestion_runs` (`id`),
  CONSTRAINT `fk_macro_observation_series` FOREIGN KEY (`series_id`) REFERENCES `macro_series` (`id`),
  CONSTRAINT `chk_macro_observation_availability` CHECK (((`available_at_utc` <= `ingested_at_utc`) or (`availability_confidence` in (_utf8mb4'retrieval_only',_utf8mb4'unknown')))),
  CONSTRAINT `chk_macro_observation_value` CHECK (((`decimal_value` is null) <> (`text_value` is null)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `macro_snapshot_observations` (
  `snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `observation_id` bigint unsigned NOT NULL,
  `factor_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`snapshot_id`,`observation_id`),
  KEY `idx_macro_snapshot_observation_reverse` (`observation_id`,`snapshot_id`),
  KEY `idx_macro_snapshot_factor` (`snapshot_id`,`factor_code`,`observation_id`),
  CONSTRAINT `fk_macro_snapshot_observation_snapshot` FOREIGN KEY (`snapshot_id`) REFERENCES `macro_research_snapshots` (`id`),
  CONSTRAINT `fk_macro_snapshot_observation_value` FOREIGN KEY (`observation_id`) REFERENCES `macro_observations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
