-- Append-only evidence association. Activation requires independent schema readiness.
-- Existing terminal history JSON, hashes and ownership are never rewritten here.
CREATE TABLE terminal_history_order_provenance_v4 (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  terminal_history_order_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  trading_account_id BIGINT UNSIGNED NOT NULL,
  user_id INT NOT NULL,
  platform ENUM('mt4','mt5') NOT NULL,
  terminal_instance_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  terminal_profile_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  broker_server VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  account_login VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  connection_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  connection_epoch BIGINT UNSIGNED NOT NULL,
  ownership_revision BIGINT UNSIGNED NOT NULL,
  request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  query_message_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  response_message_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_revision VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_kind ENUM('terminal','local_projection') NOT NULL,
  fact_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provenance_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  observed_at_utc DATETIME(3) NOT NULL,
  received_at_utc DATETIME(3) NOT NULL,
  created_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_history_order_provenance_response (terminal_history_order_id,response_message_id),
  KEY idx_history_order_provenance_identity (trading_account_id,terminal_instance_id,terminal_history_order_id),
  CONSTRAINT fk_history_order_provenance_order FOREIGN KEY (terminal_history_order_id) REFERENCES terminal_history_orders_v4 (id),
  CONSTRAINT fk_history_order_provenance_account FOREIGN KEY (trading_account_id) REFERENCES trading_accounts (id),
  CONSTRAINT fk_history_order_provenance_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT chk_history_order_provenance_revisions CHECK (connection_epoch>0 AND ownership_revision>0),
  CONSTRAINT chk_history_order_provenance_hashes CHECK (fact_sha256 REGEXP '^[0-9a-f]{64}$' AND provenance_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
