-- Isolated V4 inference/decision build namespace only; preserve all legacy tables.
-- Apply only through a verified append-only coordinator after backup and parent admission.

CREATE TABLE `inference_snapshots_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `purpose` enum('analysis','trader') COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned DEFAULT NULL,
  `strategy_id` bigint unsigned NOT NULL,
  `strategy_version_id` bigint unsigned NOT NULL,
  `standard_symbol` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_bytes` bigint unsigned NOT NULL,
  `captured_at_utc` datetime(3) NOT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inference_snapshot_payload_hash` (`purpose`,`user_id`,`payload_sha256`),
  KEY `idx_inference_snapshots_user` (`user_id`,`purpose`,`created_at_utc`,`id`),
  KEY `idx_inference_snapshots_account` (`trading_account_id`,`purpose`,`created_at_utc`,`id`),
  KEY `fk_inference_snapshots_strategy` (`strategy_id`),
  KEY `fk_inference_snapshots_strategy_version` (`strategy_version_id`,`strategy_id`),
  CONSTRAINT `build_inf_c86d439b34a23c6959ec8bfc` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_37a482f0f6a622d4cbf7ba51` FOREIGN KEY (`strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_inf_d744497b3fe127ab6f7ca36e` FOREIGN KEY (`strategy_version_id`, `strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_inf_15a94f5bb0f6d57e59233511` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `build_inf_544ff768772ee2003b16e92b` CHECK ((((`purpose` = _utf8mb4'analysis') and (`trading_account_id` is null)) or ((`purpose` = _utf8mb4'trader') and (`trading_account_id` is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `inference_snapshot_payloads_v4_build` (
  `snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `encoding` enum('json') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'json',
  `payload_json` json NOT NULL,
  PRIMARY KEY (`snapshot_id`),
  CONSTRAINT `build_inf_f9afae7e9c71fae06bc7df0e` FOREIGN KEY (`snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_model_tasks_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `purpose` enum('analysis','trader') COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned DEFAULT NULL,
  `input_snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `model_profile_id` bigint unsigned DEFAULT NULL,
  `status` enum('queued','running','succeeded','failed','cancelled','expired') COLLATE utf8mb4_unicode_ci NOT NULL,
  `deadline_at_utc` datetime(3) NOT NULL,
  `fencing_token` bigint unsigned NOT NULL,
  `lease_owner` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `lease_expires_at_utc` datetime(3) DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_model_tasks_worker` (`purpose`,`status`,`created_at_utc`,`id`),
  KEY `idx_ai_model_tasks_user` (`user_id`,`created_at_utc`,`id`),
  KEY `fk_ai_model_tasks_snapshot` (`input_snapshot_id`),
  KEY `idx_ai_model_tasks_lease` (`status`,`lease_expires_at_utc`,`id`),
  KEY `idx_ai_model_tasks_account_lease` (`trading_account_id`,`purpose`,`status`,`lease_expires_at_utc`,`id`),
  CONSTRAINT `build_inf_c5bd3bc0267d7b28ad294bfc` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_ea6a85c5635a874974888a5d` FOREIGN KEY (`input_snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`),
  CONSTRAINT `build_inf_b57695181409e75e254b094d` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_model_attempts_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `task_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `attempt_number` int unsigned NOT NULL,
  `provider` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `model` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` enum('running','succeeded','failed','timed_out','contract_invalid') COLLATE utf8mb4_unicode_ci NOT NULL,
  `started_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  `usage_json` json DEFAULT NULL,
  `error_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_model_attempt_number` (`task_id`,`attempt_number`),
  KEY `idx_ai_model_attempts_status` (`status`,`started_at_utc`,`id`),
  CONSTRAINT `build_inf_0ca28edb78f1f938223793b5` FOREIGN KEY (`task_id`) REFERENCES `ai_model_tasks_v4_build` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_analysis_runs_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `user_id` int NOT NULL,
  `strategy_id` bigint unsigned NOT NULL,
  `strategy_version_id` bigint unsigned NOT NULL,
  `standard_symbol` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `market_source_account_id` bigint unsigned DEFAULT NULL,
  `trigger_type` enum('manual','scheduled','event') COLLATE utf8mb4_unicode_ci NOT NULL,
  `schedule_slot_utc` datetime(3) DEFAULT NULL,
  `idempotency_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `input_snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `model_task_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `status` enum('queued','running','succeeded','failed','cancelled','expired') COLLATE utf8mb4_unicode_ci NOT NULL,
  `error_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_analysis_idempotency` (`user_id`,`idempotency_key`),
  UNIQUE KEY `uk_ai_analysis_schedule` (`user_id`,`strategy_version_id`,`standard_symbol`,`schedule_slot_utc`),
  KEY `idx_ai_analysis_history` (`user_id`,`created_at_utc`,`id`),
  KEY `idx_ai_analysis_worker` (`status`,`created_at_utc`,`id`),
  KEY `fk_ai_analysis_strategy` (`strategy_id`),
  KEY `fk_ai_analysis_strategy_version` (`strategy_version_id`,`strategy_id`),
  KEY `fk_ai_analysis_snapshot` (`input_snapshot_id`),
  KEY `fk_ai_analysis_model_task` (`model_task_id`),
  KEY `idx_ai_analysis_source` (`market_source_account_id`,`created_at_utc`,`id`),
  CONSTRAINT `build_inf_dd529a8d821bc06ade687abb` FOREIGN KEY (`model_task_id`) REFERENCES `ai_model_tasks_v4_build` (`id`),
  CONSTRAINT `build_inf_27ea9c331efc2766f4c88db0` FOREIGN KEY (`input_snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`),
  CONSTRAINT `build_inf_ad95042daa038008f502f6d4` FOREIGN KEY (`market_source_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_82e6985200834ada8b0db123` FOREIGN KEY (`strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_inf_900edb42e6f532cea5f6c579` FOREIGN KEY (`strategy_version_id`, `strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_inf_c169a89664bbda0042a99e6d` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `market_analyses_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `analysis_run_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `owner_scope` enum('platform','user') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `owner_user_id` int DEFAULT NULL,
  `strategy_id` bigint unsigned NOT NULL,
  `strategy_version_id` bigint unsigned NOT NULL,
  `standard_symbol` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `market_bias` enum('bullish','bearish','neutral','uncertain') COLLATE utf8mb4_unicode_ci NOT NULL,
  `opportunity` enum('none','long_setup','short_setup') COLLATE utf8mb4_unicode_ci NOT NULL,
  `confidence` decimal(5,2) NOT NULL,
  `summary` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `input_snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `content_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `analyzed_at_utc` datetime(3) NOT NULL,
  `valid_until_utc` datetime(3) NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `legacy_source_table` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `legacy_id` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_market_analyses_run` (`analysis_run_id`),
  UNIQUE KEY `uk_market_analyses_legacy` (`legacy_source_table`,`legacy_id`),
  KEY `idx_market_analyses_user` (`owner_user_id`,`created_at_utc`,`id`),
  KEY `idx_market_analyses_strategy_symbol` (`strategy_id`,`standard_symbol`,`created_at_utc`,`id`),
  KEY `fk_market_analyses_strategy_version` (`strategy_version_id`,`strategy_id`),
  KEY `fk_market_analyses_snapshot` (`input_snapshot_id`),
  CONSTRAINT `build_inf_97fce77d611ca2d4bf21af1f` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `build_inf_5af34c29eac6ba73de991fb1` FOREIGN KEY (`analysis_run_id`) REFERENCES `ai_analysis_runs_v4_build` (`id`),
  CONSTRAINT `build_inf_b8d2f00897dd8adb7d311814` FOREIGN KEY (`input_snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`),
  CONSTRAINT `build_inf_e2e9573b5c5851425eb7900b` FOREIGN KEY (`strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_inf_d2611a93717bf755bfec2a40` FOREIGN KEY (`strategy_version_id`, `strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_inf_45030330436e37974a7cc67b` CHECK (((`confidence` >= 0) and (`confidence` <= 100))),
  CONSTRAINT `build_inf_4ca8c4d56cafcd921f61d1cb` CHECK ((((`owner_scope` = _utf8mb4'platform') and (`owner_user_id` is null)) or ((`owner_scope` = _utf8mb4'user') and (`owner_user_id` is not null)))),
  CONSTRAINT `build_inf_5adbd1951ed9b5e4e44f7e31` CHECK ((`valid_until_utc` > `analyzed_at_utc`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `market_analysis_payloads_v4_build` (
  `market_analysis_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_json` json NOT NULL,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_bytes` bigint unsigned NOT NULL,
  PRIMARY KEY (`market_analysis_id`),
  CONSTRAINT `build_inf_286c1f3a5abf4696e9a145d9` FOREIGN KEY (`market_analysis_id`) REFERENCES `market_analyses_v4_build` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_trader_runs_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned NOT NULL,
  `subscription_revision` bigint unsigned NOT NULL,
  `market_analysis_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `strategy_id` bigint unsigned NOT NULL,
  `strategy_version_id` bigint unsigned NOT NULL,
  `task_mode` enum('entry','manage','both') COLLATE utf8mb4_unicode_ci NOT NULL,
  `analysis_revision` bigint unsigned NOT NULL DEFAULT '1',
  `account_revision` bigint unsigned DEFAULT NULL,
  `quote_revision` bigint unsigned DEFAULT NULL,
  `contract_revision` bigint unsigned DEFAULT NULL,
  `risk_revision` bigint unsigned DEFAULT NULL,
  `positions_revision` bigint unsigned NOT NULL DEFAULT '0',
  `pending_orders_revision` bigint unsigned NOT NULL DEFAULT '0',
  `idempotency_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `input_snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `model_task_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `status` enum('queued','running','succeeded','failed','cancelled','expired') COLLATE utf8mb4_unicode_ci NOT NULL,
  `error_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at_utc` datetime(3) NOT NULL,
  `updated_at_utc` datetime(3) NOT NULL,
  `completed_at_utc` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_trader_target` (`market_analysis_id`,`subscription_id`,`trading_account_id`,`subscription_revision`,`strategy_version_id`),
  UNIQUE KEY `uk_ai_trader_idempotency` (`user_id`,`idempotency_key`),
  KEY `idx_ai_trader_account` (`trading_account_id`,`created_at_utc`,`id`),
  KEY `idx_ai_trader_worker` (`status`,`created_at_utc`,`id`),
  KEY `fk_ai_trader_subscription` (`subscription_id`),
  KEY `fk_ai_trader_strategy` (`strategy_id`),
  KEY `fk_ai_trader_strategy_version` (`strategy_version_id`,`strategy_id`),
  KEY `fk_ai_trader_snapshot` (`input_snapshot_id`),
  KEY `fk_ai_trader_model_task` (`model_task_id`),
  CONSTRAINT `build_inf_74c1dfba66ec6aabea9a24ef` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_4f5a6112fdd30750fca34809` FOREIGN KEY (`market_analysis_id`) REFERENCES `market_analyses_v4_build` (`id`),
  CONSTRAINT `build_inf_34bcfbca16c0eeea5d67abd9` FOREIGN KEY (`model_task_id`) REFERENCES `ai_model_tasks_v4_build` (`id`),
  CONSTRAINT `build_inf_855d8ea12f63231125056a9e` FOREIGN KEY (`input_snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`),
  CONSTRAINT `build_inf_2e2bc6c7f719003f523e5169` FOREIGN KEY (`strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_inf_23e635cc46a94d900a2abf58` FOREIGN KEY (`strategy_version_id`, `strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_inf_b8a7d27c436c902fe45c961a` FOREIGN KEY (`subscription_id`) REFERENCES `strategy_subscriptions_v4_build` (`id`),
  CONSTRAINT `build_inf_f77611e8b8ceee5174cf6f1f` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `trade_decisions_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `trader_run_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned NOT NULL,
  `market_analysis_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `strategy_id` bigint unsigned NOT NULL,
  `strategy_version_id` bigint unsigned NOT NULL,
  `action_kind` enum('hold','market_order','pending_order','modify_position','close_position','modify_order','cancel_order') COLLATE utf8mb4_unicode_ci NOT NULL,
  `side` enum('buy','sell') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confidence` decimal(5,2) NOT NULL,
  `summary` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `input_snapshot_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `content_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` enum('proposed','stale','risk_rejected','accepted') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'proposed',
  `stale_reason` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `risk_decision_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trade_decisions_run` (`trader_run_id`),
  UNIQUE KEY `uk_trade_decision_risk` (`risk_decision_id`),
  KEY `idx_trade_decisions_account` (`trading_account_id`,`created_at_utc`,`id`),
  KEY `idx_trade_decisions_analysis` (`market_analysis_id`,`trading_account_id`,`id`),
  KEY `fk_trade_decisions_user` (`user_id`),
  KEY `fk_trade_decisions_strategy` (`strategy_id`),
  KEY `fk_trade_decisions_strategy_version` (`strategy_version_id`,`strategy_id`),
  KEY `fk_trade_decisions_snapshot` (`input_snapshot_id`),
  CONSTRAINT `build_inf_0740be2c90774cd9e3b8f32c` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_3b9c04485778d1c93b5a5ad9` FOREIGN KEY (`market_analysis_id`) REFERENCES `market_analyses_v4_build` (`id`),
  CONSTRAINT `build_inf_8ae2b167ba9b0743ddaefb7f` FOREIGN KEY (`trader_run_id`) REFERENCES `ai_trader_runs_v4_build` (`id`),
  CONSTRAINT `build_inf_12a3ff95db57c0e8ddc81a23` FOREIGN KEY (`input_snapshot_id`) REFERENCES `inference_snapshots_v4_build` (`id`),
  CONSTRAINT `build_inf_1c4afc38a8809f954434c06c` FOREIGN KEY (`strategy_id`) REFERENCES `strategies` (`id`),
  CONSTRAINT `build_inf_7a01f47f1db675d867c684d4` FOREIGN KEY (`strategy_version_id`, `strategy_id`) REFERENCES `strategy_versions` (`id`, `strategy_id`),
  CONSTRAINT `build_inf_237346b062143ea85b1c19bd` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `build_inf_b90dc065f01848988e931db5` CHECK (((`confidence` >= 0) and (`confidence` <= 100)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `trade_decision_payloads_v4_build` (
  `trade_decision_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_json` json NOT NULL,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_bytes` bigint unsigned NOT NULL,
  PRIMARY KEY (`trade_decision_id`),
  CONSTRAINT `build_inf_d81a2845681bc54c76ab2681` FOREIGN KEY (`trade_decision_id`) REFERENCES `trade_decisions_v4_build` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `risk_decisions_v4_build` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `trade_decision_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `user_id` int NOT NULL,
  `trading_account_id` bigint unsigned NOT NULL,
  `platform_policy_version_id` bigint unsigned NOT NULL,
  `account_policy_version_id` bigint unsigned DEFAULT NULL,
  `policy_set_revision` bigint unsigned NOT NULL,
  `account_risk_revision` bigint unsigned NOT NULL,
  `decision_status` enum('approved','rejected') COLLATE utf8mb4_unicode_ci NOT NULL,
  `reject_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `policy_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `legacy_source_table` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `legacy_id` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at_utc` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_risk_decision_trade_decision` (`trade_decision_id`),
  UNIQUE KEY `uk_risk_decision_legacy` (`legacy_source_table`,`legacy_id`),
  KEY `idx_risk_decision_account` (`user_id`,`trading_account_id`,`created_at_utc`,`id`),
  KEY `idx_risk_decision_status` (`decision_status`,`created_at_utc`,`id`),
  KEY `fk_risk_decision_account` (`trading_account_id`),
  KEY `fk_risk_decision_platform_policy` (`platform_policy_version_id`),
  KEY `fk_risk_decision_account_policy` (`account_policy_version_id`),
  CONSTRAINT `build_inf_1408092cb77dd9ba1ccd31f2` FOREIGN KEY (`trading_account_id`) REFERENCES `trading_accounts` (`id`),
  CONSTRAINT `build_inf_e43675f95ef8db37e5d34c99` FOREIGN KEY (`account_policy_version_id`) REFERENCES `risk_policy_versions_v4` (`id`),
  CONSTRAINT `build_inf_dddef97403c671d093ba0f98` FOREIGN KEY (`platform_policy_version_id`) REFERENCES `risk_policy_versions_v4` (`id`),
  CONSTRAINT `build_inf_fcad85ec3743434f847c77ff` FOREIGN KEY (`trade_decision_id`) REFERENCES `trade_decisions_v4_build` (`id`),
  CONSTRAINT `build_inf_ca6c6bc2591479ec688ff5c8` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `build_inf_135944e44cc984c2a84008e4` CHECK ((((`decision_status` = _utf8mb4'approved') and (`reject_code` is null)) or ((`decision_status` = _utf8mb4'rejected') and (`reject_code` is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `risk_decision_payloads_v4_build` (
  `risk_decision_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `evaluation_json` json NOT NULL,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_bytes` bigint unsigned NOT NULL,
  PRIMARY KEY (`risk_decision_id`),
  CONSTRAINT `build_inf_8bb1b90ce107458b02ada1f1` FOREIGN KEY (`risk_decision_id`) REFERENCES `risk_decisions_v4_build` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `trade_decisions_v4_build` ADD CONSTRAINT `build_inf_83956b0400318cd49a2b3277` FOREIGN KEY (`risk_decision_id`) REFERENCES `risk_decisions_v4_build` (`id`);
