CREATE TABLE IF NOT EXISTS terminal_clock_observations_v4 (
  trading_account_id BIGINT UNSIGNED NOT NULL,
  projection_revision BIGINT UNSIGNED NOT NULL,
  user_id INT NOT NULL,
  ownership_interval_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  ownership_revision BIGINT UNSIGNED NOT NULL,
  terminal_profile_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  terminal_instance_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  connection_epoch BIGINT UNSIGNED NOT NULL,
  connection_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  reported_offset_minutes SMALLINT NULL,
  reported_status ENUM('calibrated','observer_bootstrap','stale','unavailable') NOT NULL,
  effective_offset_minutes SMALLINT NULL,
  effective_status ENUM('calibrated','observer_bootstrap','stale','unavailable') NOT NULL,
  observed_at_utc DATETIME(3) NOT NULL,
  received_at_utc DATETIME(3) NOT NULL,
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (trading_account_id,projection_revision),
  KEY idx_clock_observation_history (trading_account_id,ownership_interval_id,observed_at_utc,projection_revision),
  CONSTRAINT fk_clock_observation_account FOREIGN KEY (trading_account_id) REFERENCES trading_accounts (id),
  CONSTRAINT fk_clock_observation_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_clock_observation_interval FOREIGN KEY (ownership_interval_id) REFERENCES trading_account_ownership_intervals (id),
  CONSTRAINT fk_clock_observation_profile FOREIGN KEY (terminal_profile_id) REFERENCES terminal_profiles (id),
  CONSTRAINT chk_clock_observation_reported CHECK (reported_offset_minutes BETWEEN -840 AND 840),
  CONSTRAINT chk_clock_observation_effective CHECK (effective_offset_minutes BETWEEN -840 AND 840),
  CONSTRAINT chk_clock_observation_calibrated CHECK (reported_status NOT IN ('calibrated','observer_bootstrap') OR reported_offset_minutes IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
