CREATE TABLE IF NOT EXISTS period_review_workflows_v4 (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  user_id INT NOT NULL,
  trading_account_id BIGINT UNSIGNED NOT NULL,
  ownership_interval_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  period_kind ENUM('daily','monthly') NOT NULL,
  period_key VARCHAR(10) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  phase ENUM('planning','history','succeeded') NOT NULL,
  progress_json JSON NOT NULL,
  progress_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  attempts BIGINT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at_utc DATETIME(3) NULL,
  last_reason VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  created_at_utc DATETIME(3) NOT NULL,
  updated_at_utc DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_period_workflow_scope (user_id,trading_account_id,ownership_interval_id,period_kind,period_key),
  KEY idx_period_workflow_due (phase,next_attempt_at_utc,id),
  CONSTRAINT fk_period_workflow_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_period_workflow_account FOREIGN KEY (trading_account_id) REFERENCES trading_accounts (id),
  CONSTRAINT fk_period_workflow_interval FOREIGN KEY (ownership_interval_id) REFERENCES trading_account_ownership_intervals (id),
  CONSTRAINT chk_period_workflow_due CHECK ((phase='succeeded' AND next_attempt_at_utc IS NULL) OR (phase<>'succeeded' AND next_attempt_at_utc IS NOT NULL)),
  CONSTRAINT chk_period_workflow_phase CHECK (JSON_UNQUOTE(JSON_EXTRACT(progress_json,'$.phase'))=phase)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
