// Generated by scripts/generate-execution-workflow-schema-readiness.mjs; do not edit.
export const executionWorkflowSchema = {
  "steps": [
    {
      "id": "inplace_001_01_users_last_seen_at_utc",
      "checksum": "cd91b878646811a8ad3604e9861c7f5d19dd8afa9eb4b287dcfd0c1b6ae683d4"
    },
    {
      "id": "inplace_001_02_users_profile_revision",
      "checksum": "a053ce52693557d13f7cb4973b67889f0b5e451973b6366a1ceed807f01e5ef1"
    },
    {
      "id": "inplace_001_03_bridge_refresh_sessions_credential_version",
      "checksum": "453d8c021b9030198d3315c4b23efd99e0bda3b6394c28b030d5e89444c10cac"
    },
    {
      "id": "inplace_001_04_bridge_refresh_sessions_installation_id",
      "checksum": "ae9bc21f503e64360e6cbe144fb057d2038a7969749dbd372079d30dc9a6ec60"
    },
    {
      "id": "inplace_001_05_bridge_refresh_sessions_profile_id",
      "checksum": "1852e848e099d078ad5ff184a2570d8c082297b7df4e3141281c7122f62311ef"
    },
    {
      "id": "inplace_001_06_bridge_refresh_sessions_generation",
      "checksum": "8957dba504685e97a3ebe8d84d0d3bd049800d39c5782f5fa94f06fff7361669"
    },
    {
      "id": "inplace_001_07_bridge_refresh_sessions_migration_key",
      "checksum": "9a2263e53e38ca20a60da68e3f014cdece5be6e891e731dc7a0a3e5402e71b87"
    },
    {
      "id": "inplace_001_08_bridge_refresh_sessions_source_fingerprint",
      "checksum": "c1c57acee488ff3a68ea900f725ead51abb1438954179fe6ed727286c5196ab0"
    },
    {
      "id": "inplace_001_09_bridge_refresh_sessions_source_refresh_session_id",
      "checksum": "2746ee2692c307e74b493831d2f918a33e1e325f6812448ff47657e81780c115"
    },
    {
      "id": "inplace_002_01_auth_sessions",
      "checksum": "48f6d3796a7a0f8a862ef477e69b5cd97c346e3284ebbf9170788d4156bd0e4a"
    },
    {
      "id": "inplace_002_02_auth_authorization_codes",
      "checksum": "158ee33d5c0e1359e2b777b8c01a009e3b47f4443baf1193a5baf839694de365"
    },
    {
      "id": "inplace_002_03_terminal_profiles",
      "checksum": "d6d2a687adce9d5c9280a00f6ac4f3a5b08932ae7613106c36d193b9daa1d688"
    },
    {
      "id": "inplace_002_04_bridge_connection_capacity_grants",
      "checksum": "a5f23554dad296277da0863d49215cf9402fec71079f3e04ed5ffdb222025058"
    },
    {
      "id": "inplace_002_05_data_migration_runs",
      "checksum": "ffe6d67303fa66e5e5ef90a2057ea93e3c3918f0789a18531c2db472b94a6a30"
    },
    {
      "id": "inplace_002_06_data_migration_checkpoints",
      "checksum": "0f9217892fa398c076967967a86319a25d55998f6ec51b356bffad73099d1271"
    },
    {
      "id": "inplace_002_07_data_migration_batches",
      "checksum": "af28984895255bebe9530a5203873528229345d1ec8311464b6ddaf3f62dab38"
    },
    {
      "id": "inplace_002_08_data_migration_id_maps",
      "checksum": "8af2fc24d9cb4bef9cbfb39c74e4edcd59237af990731d3649d678e0b38401fd"
    },
    {
      "id": "inplace_002_09_data_migration_row_receipts",
      "checksum": "ccddcf2dd2b1be9ae89dd1cbfd89963a68d3658765df3357c73e0ed13b18a02b"
    },
    {
      "id": "inplace_003_01_trading_accounts_v4_build",
      "checksum": "814f7b8a5f07a344b21371952a2107417d36498b26b361ac0bbc19c331768e1d"
    },
    {
      "id": "inplace_003_02_trading_account_ownership_intervals_v4_build",
      "checksum": "f1cae5e187123c4c26b3072b0901cf2099c113fbb7d7057c79fb33ca0c9c6560"
    },
    {
      "id": "inplace_003_03_trading_account_ownerships_v4_build",
      "checksum": "12c5bc764f95c4fb06a9391c0017adb73c0c7bf8f0be6f18ffbde38a30dab307"
    },
    {
      "id": "inplace_003_04_user_trading_account_settings_v4_build",
      "checksum": "54440c8bcf20c4ebad8cda1cb9d5e169b004ed7a4b35cb49063fc1145a489998"
    },
    {
      "id": "inplace_004_01_data_migration_source_rows",
      "checksum": "b8855e891a7cf3e7830a8b4311844764f42078c2a5f72fbed6d0954e101026fe"
    },
    {
      "id": "inplace_005_01_strategies",
      "checksum": "c3ecdab295a7e4acaf102d5521696316adf07eb00468e4a5c43d6bc16fe25dbb"
    },
    {
      "id": "inplace_005_02_strategy_versions",
      "checksum": "0821d9ae7c6322b0d7ade0feea07cfd14c929f8cdebc9ffac0bba876c01acd35"
    },
    {
      "id": "inplace_005_03_strategy_active_version_fk",
      "checksum": "24dbdf2987fa31116e323445724e436eb7083bb99e1a6d8a1900ac3c76ed1b9e"
    },
    {
      "id": "inplace_006_01_strategy_subscriptions_v4_build",
      "checksum": "d8684953218327f93648a3dfe29ca37b8fdef43b987e53018c2db3034906fb85"
    },
    {
      "id": "inplace_006_02_subscription_schedules_v4_build",
      "checksum": "b9b7ae1e00e9516b89871419c270ce9774a8d5a2a684eca21455ee21cbe644a3"
    },
    {
      "id": "inplace_006_03_subscription_execution_preferences_v4_build",
      "checksum": "d92169c09ad04d95739764520628b77c84e29df573311cbce825ba8e19db06c6"
    },
    {
      "id": "inplace_007_01_macro_data_sources",
      "checksum": "f097a9203ee9c42ec600f31426206dfa0f80a60850b8a3b44dca025bb91d7d50"
    },
    {
      "id": "inplace_007_02_macro_feature_sets",
      "checksum": "a77d64fb56d61475cd22751d9389ce2c6db3e128f2334c1a9b61938efa96457e"
    },
    {
      "id": "inplace_007_03_economic_calendar_events",
      "checksum": "babea2c19e0472cdab74dd1f811397cca252f9cb644bc0605a1575a039269244"
    },
    {
      "id": "inplace_007_04_macro_model_versions",
      "checksum": "13087d6d040b71ff3e133f674383afa47aa84f69435161a570e3531644d29472"
    },
    {
      "id": "inplace_007_05_macro_series",
      "checksum": "4b4afcff292a65452a02d409ed6c1480f27c972daa7a7af8e749dbc690860097"
    },
    {
      "id": "inplace_007_06_macro_ingestion_runs",
      "checksum": "c6b2c2af4711f4dded71b21bf989c61d9395f0026a106017d43fe84c725b42d3"
    },
    {
      "id": "inplace_007_07_macro_pipeline_jobs",
      "checksum": "b23105c181e179883f67afee13f311667f59caa6eacbf0a5cb76aa19d6ea94d9"
    },
    {
      "id": "inplace_007_08_macro_research_snapshots",
      "checksum": "1ba69c93544432bed23a00b30fb7e12880318fbaf6311be63be01203ed81e549"
    },
    {
      "id": "inplace_007_09_economic_calendar_event_revisions",
      "checksum": "3f3edf91efa5b51b30cef1b4f4af8d1e2b4d6540becfdbb0d75e17f1c94b1cd6"
    },
    {
      "id": "inplace_007_10_macro_observations",
      "checksum": "805bf7acc583133e9193aa3954898a2caf6628d7760852942a9c2651b2487708"
    },
    {
      "id": "inplace_007_11_macro_snapshot_observations",
      "checksum": "299b73c3d71e879073acc812fc44ce0a710924a3882998960e453c4c16c3f01c"
    },
    {
      "id": "inplace_008_01_email_verified",
      "checksum": "3cb9c7ca5b1a9619762e26072e522796ece8b92d394b4c852e35ceea4496a0db"
    },
    {
      "id": "inplace_008_02_phone_verified",
      "checksum": "c9e83af6764f0c293ca4c354585a267cf47f1ab5ad90ba0c9da6337c3ffdc46f"
    },
    {
      "id": "inplace_008_03_auth_method",
      "checksum": "faa3d03e6dbf1597751152804be99e95834fb4a9e65aa355596e9fbe2dd9645d"
    },
    {
      "id": "inplace_008_04_plan_period",
      "checksum": "f656c8b10a32df7705ba03d3346b95059ce81b5bd6c452a72f2845dd35b1eeb1"
    },
    {
      "id": "inplace_008_05_changelog_seen_version",
      "checksum": "278dce48dc118a9f41ab9940f998ab5e0ffd281504d03a55d9ce626bfc647d8f"
    },
    {
      "id": "inplace_009_01_user_referral_accounts",
      "checksum": "38b5b9cc45c45be8d4c87eb63034156fea1e96b1200ffe6fa7754f1f7396dc75"
    },
    {
      "id": "inplace_010_01_referral_credit_ledger",
      "checksum": "dc08b3299d5b02ec1f0b5e3fe834820ad5c2a0324dc197aa94f7d52742d11623"
    },
    {
      "id": "inplace_011_01_payment_orders",
      "checksum": "20a8fd7437933a6539ba452c42aeab1655dd3ab531d49ccd6c2e1f636416a1cd"
    },
    {
      "id": "inplace_012_01_payment_transactions",
      "checksum": "aabf96ede051bd3f736594e960d88ea1cec63db2191fb110153fbdd5709ff094"
    },
    {
      "id": "inplace_012_02_payment_matches",
      "checksum": "92b73a42434056d3f8bdc3d5504f59c67e163f0d0b979aed51d2b4419a262eed"
    },
    {
      "id": "inplace_013_01_memberships",
      "checksum": "a18948f4bbb414624e08094855bd8ab28bb488971e47b97d22ff9b5cff39548e"
    },
    {
      "id": "inplace_014_01_referral_rule_constraints",
      "checksum": "91cb456434338ec836ca3cee9ddcd732cd18433a29479eded6ebfce15825545e"
    },
    {
      "id": "inplace_015_01_referral_rule_changes",
      "checksum": "6179a0daf0870f0df5f2257d5ad08bd5b45f498aee072df8b6c3139df2bcd104"
    },
    {
      "id": "inplace_016_01_payment_wallet_addresses",
      "checksum": "70c669449cce43fa3b90a31fa23f65d2166184f0d1a59b660e11f6449aa7ec9e"
    },
    {
      "id": "inplace_017_01_system_settings",
      "checksum": "9e6d781a58520190c2c33763465f1bb7bd3475d542725bd5e27a0f7d295aba08"
    },
    {
      "id": "inplace_017_02_system_setting_changes",
      "checksum": "7059f04fd2e38b1e18ae5a6888fadbb04e3d25a4085e7ee5a961a2e0251fe226"
    },
    {
      "id": "inplace_017_03_system_settings_exact_tokens",
      "checksum": "f02a59a74656605820c8dbe0796ba2575c3acdb4c4c665c9a7756412caac87d4"
    },
    {
      "id": "inplace_018_01_system_setting_requests",
      "checksum": "7390a2389320f6ae18bd9d1db4fec9e81678d024f8cad3c9524c2bbc26cf8df9"
    },
    {
      "id": "inplace_019_01_learning_courses",
      "checksum": "e2096e95c5e3337b761c40a74ae49ce832e837915d715e79a219fa45e1092e90"
    },
    {
      "id": "inplace_019_02_learning_lessons",
      "checksum": "5e507c9536d5e8c1d1dce6f759a505b354de7c8328e4100e8f18cb0ea048a533"
    },
    {
      "id": "inplace_019_03_learning_media_references",
      "checksum": "1bd2f0482128fadb86b66169694be047dc116544e867516fbf85ba37a91604d1"
    },
    {
      "id": "inplace_019_04_learning_progress",
      "checksum": "d283dcde4954506e5979a66ad79edce32380219b55ea036897b87f12ab7522e7"
    },
    {
      "id": "inplace_020_01_learning_progress_changes",
      "checksum": "d306aa96f1f497c10713be46ad18e6d5566f80829e4cde159284e87ac59af9f2"
    },
    {
      "id": "inplace_020_02_learning_request_key_preservation",
      "checksum": "d3d1c3f0f5261562521d1555bd74237a6f3e795c7dfd5879b4ae1a65fac4434a"
    },
    {
      "id": "inplace_021_01_ai_manual_analysis_cooldowns",
      "checksum": "edc8d2fae405638e64d1019497091335c3cadf87689eacf31e75f161233635b4"
    },
    {
      "id": "inplace_021_02_outbox_events",
      "checksum": "28b33b0afd6274afa031dbab1804b80a597062bf24f71309754c47644bb6ad9a"
    },
    {
      "id": "inplace_021_03_global_risk_controls",
      "checksum": "cd79ab88baaff16508e97ff17079bf28d6660cbd7f3140d9401a0c364bb27611"
    },
    {
      "id": "inplace_021_04_strategy_memory_libraries_v4",
      "checksum": "0eae3fd01c51fac709cc62322fa6cc47e5dade20ebfb723692b0ca05c0f7e5c6"
    },
    {
      "id": "inplace_021_05_strategy_memory_library_revisions_v4",
      "checksum": "e2f6f2eebcb521a6492444d13b08343eef574e55e30f878f8a6ebfed23d7fa0a"
    },
    {
      "id": "inplace_021_06_strategy_memory_libraries_v4",
      "checksum": "d2699c8732009dd1c674dd88a8fe05bc3ddda71548bcaf82eadb2efeda56347d"
    },
    {
      "id": "inplace_021_07_strategy_memory_injection_logs_v4",
      "checksum": "4552716fbfaf2c17d1929ef56cd01bf638b80b9958a4a54886cbe0e3db8eb455"
    },
    {
      "id": "inplace_021_08_trade_history_migration_checkpoints_v4",
      "checksum": "631ddee0d8e680c90eb703281c993e39780e0a4d735fb1f1d1e540f6ac76d8fc"
    },
    {
      "id": "inplace_021_09_observer_management_registry",
      "checksum": "17ff0fcedc1ba6b276aeca89cfb8d7d14e1373b4d1686f3bff632e14a203c76a"
    },
    {
      "id": "inplace_021_10_observer_management_operations",
      "checksum": "81ef088e84131690a8aa317f7e7e89391b7c27dea721feeccfa310751de9046f"
    },
    {
      "id": "inplace_021_11_bridge_v4_pairing_requests",
      "checksum": "eb3cd948d2c2d9b6cf43298d064c99d9ec74b9acfb1694c1bea6ee79c1234987"
    },
    {
      "id": "inplace_022_01_users_plan_expires_at",
      "checksum": "32dfa73892fa235ca4845751845bfdb74a9b653ff6d769fd21c6741b01336e2a"
    },
    {
      "id": "inplace_022_02_users_deleted_at",
      "checksum": "59078d225cd4687d1ee33872b93a7c2c6f3094155ba9859cceda0057943b3d3a"
    },
    {
      "id": "inplace_022_03_users_created_at",
      "checksum": "06c3b80d06de9a0fec1da70f60c6d09cff248dde67d3b362b99d3cc2069e26e0"
    },
    {
      "id": "inplace_022_04_users_updated_at",
      "checksum": "3e57c2b4e175f18356af3b3cb7a8376c284df8e1a2f608b92eabb89f8ebf914f"
    },
    {
      "id": "inplace_022_05_bridge_refresh_sessions_expires_at",
      "checksum": "0157d9508ea60c532128cd3c4501f1f7c43dd506bd95e84c65b1dad5e1962005"
    },
    {
      "id": "inplace_022_06_bridge_refresh_sessions_revoked_at",
      "checksum": "236c038b5e12e6f38861f66c525c9d3e1613973f1f2e08006da75967a8e3864e"
    },
    {
      "id": "inplace_022_07_bridge_refresh_sessions_last_used_at",
      "checksum": "c40d459a03d0268bb97e155e56c4ff113e5a6638188756462afa003982fd7267"
    },
    {
      "id": "inplace_022_08_bridge_refresh_sessions_created_at",
      "checksum": "5ee41a57bb7eafe732590f9791bc0ea9bd4d8d49f56a1584d6110964243fc9ac"
    },
    {
      "id": "inplace_022_09_bridge_refresh_sessions_updated_at",
      "checksum": "ccf5ae2e9d03e4fee8cf1d3fa9feb02cce38c8fbe816c78a3a82056336dd5002"
    },
    {
      "id": "inplace_022_10_ai_model_profiles_created_at",
      "checksum": "420648df2e4694c4a9921772d3a2700f14deb374ee2f3f15ae1bf98046c9f413"
    },
    {
      "id": "inplace_022_11_ai_model_profiles_updated_at",
      "checksum": "7234ac71345fadef9f1514926bd8650d5633048a5e3bfc3559482d323168c6db"
    },
    {
      "id": "inplace_022_12_ai_model_profiles_deleted_at",
      "checksum": "cbd55f97779e7c180610012d6a4f49d88d23d4ed09099318a18f19d682ecf914"
    },
    {
      "id": "inplace_022_13_user_model_defaults_created_at",
      "checksum": "dfa994ca76a3ab81200e9f04f95517e98d87ca09a384975a86c1396cc4b8721a"
    },
    {
      "id": "inplace_022_14_user_model_defaults_updated_at",
      "checksum": "35b74ca393e99061a51f9832dd4890e19e13bf7e1e88fa4653ab75a41174fc17"
    },
    {
      "id": "inplace_022_15_platform_model_usage_policy_updated_at",
      "checksum": "0965e2f07ed8ee578f4f4250fd522ab1fd24ac3489e7ab9484132a9097172676"
    },
    {
      "id": "inplace_022_16_ai_model_usage_logs_created_at",
      "checksum": "8dc88b9cc2596df206ee512f5864d647713d8b0aa1a6e8b42398b05319e60349"
    },
    {
      "id": "inplace_023_01_ai_model_profiles_provider",
      "checksum": "a4d84d2c6a6f84efa54311d20814ab053705c39494c9b6a8958f5f7144ea86b9"
    },
    {
      "id": "inplace_023_02_ai_model_profiles_model_name",
      "checksum": "a2ca71d6bf74328f8b164f14dffc77e053eacdb3d99b6b0a02bd5fa092469a75"
    },
    {
      "id": "inplace_023_03_ai_model_profiles_max_tokens",
      "checksum": "1e177bf853d53b52afa4f86a6a07325440e411a159c491c89f4f4c30fa580c49"
    },
    {
      "id": "inplace_023_04_ai_model_profiles_request_timeout_ms",
      "checksum": "39e3425cfc81a90dbe4d4c20c9a9068efdf8ce29c51102dd43fc237c083a7afb"
    },
    {
      "id": "inplace_023_05_platform_model_usage_policy_daily_requests_per_user",
      "checksum": "8c8a110c308f94e4c80d6d3b676f1881262c19326dc80f787d3bb76a11199967"
    },
    {
      "id": "inplace_023_06_platform_model_usage_policy_daily_tokens_per_user",
      "checksum": "14bad296e5edc1b9c1cc817a5b588867265b2f0522cfc4e21f91c0cc578f5f15"
    },
    {
      "id": "inplace_023_07_ai_model_usage_logs_token_count",
      "checksum": "9d749e69f17231c86ee14776d06e619adbb81f496e52a3423815e0bf715878a0"
    },
    {
      "id": "inplace_023_08_ai_model_usage_logs_request_bytes",
      "checksum": "8b1e5fdda35bbefe12b0cfb2e033b5e9c3b52133241b7d055d8fdf03d1b9b620"
    },
    {
      "id": "inplace_023_09_ai_model_usage_logs_response_bytes",
      "checksum": "8808200b110a878c32e09e13bb502a99f65ed4cbf00f5225f1f528302c879d2c"
    },
    {
      "id": "inplace_023_10_ai_model_usage_logs_duration_ms",
      "checksum": "f9905f0c17d7cfe76e41cdb39d504dd2c5af628a50fde1db459073c603ae283b"
    },
    {
      "id": "inplace_023_11_ai_model_usage_logs_input_tokens",
      "checksum": "2cd13b16d6ba7f027277eb0b8a36e3db60888abef39163f6d5d2a97a31540dc6"
    },
    {
      "id": "inplace_023_12_ai_model_usage_logs_output_tokens",
      "checksum": "1af18b2ecd520e3500366785b46564176dcf7652d20a8a24dfdd677fb59261a5"
    },
    {
      "id": "inplace_023_13_ai_model_usage_logs_reasoning_tokens",
      "checksum": "d956d8591d58370dca8c10d2735fe8717247704694b1750e1d6011aae9a5e274"
    },
    {
      "id": "inplace_023_14_ai_model_usage_logs_cached_tokens",
      "checksum": "1a27007ea311045b635fec08ec14534e9ffc80931e1580155885494eac5316f7"
    },
    {
      "id": "inplace_024_01_ai_model_usage_logs_id",
      "checksum": "750e024bc76d9eb1eabf3e1bb84fecba6539c904e330afe1243a5140f9df76f3"
    },
    {
      "id": "inplace_024_02_trading_accounts_broker_server",
      "checksum": "e6e4150dcb7be9d026c539ddfc02b249916124e36acb54d1d1d9c9e48de6ccdf"
    },
    {
      "id": "inplace_024_03_users_nickname",
      "checksum": "83a36d019a484b5e160262630dfcaa3a23e8dbcb79e9e23ac1d0088dc76d2582"
    },
    {
      "id": "inplace_024_04_users_avatar",
      "checksum": "0d08d67a43b9eb921d82ce9ef196646bb437fa78b1b7589dd001152256f656bb"
    },
    {
      "id": "inplace_024_05_users_role",
      "checksum": "a804eccc8b15603bbe6cdcac661036480eba2ca7782fac5c7678043431658b6a"
    },
    {
      "id": "inplace_024_06_users_plan",
      "checksum": "87bd644fca959c6e50abf8077b23604196d86d7a3ea03807810f73b6ef635a02"
    },
    {
      "id": "inplace_024_07_users_created_at",
      "checksum": "6185a95847705ef114ad4d8875af90a1655bd8619c006aa03ee013e511ad0024"
    },
    {
      "id": "inplace_024_08_users_updated_at",
      "checksum": "2259ece895311aa8f9cb58c93efef51abd52dcd6aec8f420c8641ac0d476b785"
    },
    {
      "id": "inplace_024_09_trading_accounts_margin_mode",
      "checksum": "d9373f399cbc02b73bbbed9f0fea93e24e3ad397af56acdab99b6bd22145c6e6"
    },
    {
      "id": "inplace_025_01_ai_model_profiles_owner_user_id",
      "checksum": "eb71ddb7c0e427228cc405f85975a66cb27a197ca93e5fdafe3efab74eae2081"
    },
    {
      "id": "inplace_025_02_ai_model_profiles_scope",
      "checksum": "01b0f7c341b21d5f78807adae13df4cf676ff6171ecba5ca9b179471cb9d34c4"
    },
    {
      "id": "inplace_025_03_ai_model_profiles_provider",
      "checksum": "75feff96052211353659bce852aca6050cd652b9346352494f4b7a207ec84aeb"
    },
    {
      "id": "inplace_025_04_ai_model_profiles_model_name",
      "checksum": "4229ce4fdc76ffd0f8748f9d9b4bc7bc17c91b4bda55dbfcc6007e67b04ec3cf"
    },
    {
      "id": "inplace_025_05_ai_model_profiles_temperature",
      "checksum": "ed5fc9685777f34b1b59257a3e98a11d9685e3f7eb77a1fdced76e90a206f679"
    },
    {
      "id": "inplace_025_06_ai_model_profiles_max_tokens",
      "checksum": "b503d4d6e00955916f95b503b9c7b10b4a62e3e3fa1c7fa92fa195f343c63b2f"
    },
    {
      "id": "inplace_025_07_ai_model_profiles_thinking_enabled",
      "checksum": "c0913a36e27da5df5fcdeca2e693026b509041d884576e96cd3172d931b7e775"
    },
    {
      "id": "inplace_025_08_ai_model_profiles_reasoning_effort",
      "checksum": "c609331a04a09abb2f5ed969b8f9e2bcea2fd542c5807729a5b37832259a37f9"
    },
    {
      "id": "inplace_025_09_ai_model_profiles_status",
      "checksum": "32d13303888d69833f348ed306dd1290df661a7c8543b38a10fff9387488ae7b"
    },
    {
      "id": "inplace_025_10_platform_model_usage_policy_id",
      "checksum": "602dbe06890077447cab91675caee4d7f4e34c8aefeade4b0843f31a95c28748"
    },
    {
      "id": "inplace_025_11_platform_model_usage_policy_daily_requests_per_user",
      "checksum": "dafc66ac107809c67653d3b32a2c785f7d5e0ed2cbfc6280d91ab3f79382c471"
    },
    {
      "id": "inplace_025_12_platform_model_usage_policy_daily_tokens_per_user",
      "checksum": "50cb996f1f0eba96937fc85712fb4ab833c0abfce117e30f1b27754a9352948f"
    },
    {
      "id": "inplace_025_13_ai_model_usage_logs_credential_source",
      "checksum": "ed5fbb91544c42874ba19578410944d95c7cf02eaa4941b3e9ead33e6b8a6344"
    },
    {
      "id": "inplace_025_14_ai_model_usage_logs_request_phase",
      "checksum": "ce8fae9698c4acc20c80ac90349abf18121b601f4090307ba597bbe56570fdc4"
    },
    {
      "id": "inplace_025_15_ai_model_usage_logs_request_status",
      "checksum": "3813da4d45b689a3c21368789aef97b3c4d119d1f27b9f80c781b20c266647d4"
    },
    {
      "id": "inplace_025_16_ai_model_usage_logs_accounting_status",
      "checksum": "d5f3a9e4784129775b3a190a22625ad65ba7b21e88a4d9491af47485d533713b"
    },
    {
      "id": "inplace_025_17_bridge_refresh_sessions_token_hash",
      "checksum": "d21f15fd9f189d18a15ff9b55ddfc481b8707dd85816482dc80f31578a803955"
    },
    {
      "id": "inplace_026_01_chk_v4_model_profiles_owner",
      "checksum": "d62bbdc459b123098097981bb2b785ed1a3faa9d4b7decb64293350a4bb064c6"
    },
    {
      "id": "inplace_026_02_chk_v4_model_policy_singleton",
      "checksum": "7ee06e2a79fb71eab1d8d7d01622fca844723e96d949135d959751c544c7fc91"
    },
    {
      "id": "inplace_027_01_uk_bridge_refresh_migration_key",
      "checksum": "91ff7a3798b3c4381bbd25d9e44a2e00a1326c86d4ecd99785fa86e324a3beca"
    },
    {
      "id": "inplace_027_02_uk_bridge_refresh_source_migration",
      "checksum": "7a4b8a01d8c9013e1cf1543e1d610c0adf1f3a3de236256a2e6cd387954188e9"
    },
    {
      "id": "inplace_027_03_idx_bridge_refresh_device",
      "checksum": "9b0d2d357dc72acecf456119553a279471c2dd188bedea4898a99823210f9daa"
    },
    {
      "id": "inplace_027_04_idx_v4_model_profiles_owner",
      "checksum": "9ee4899a9633f8358dce8f135b98855da13bebfdb8f5420d7fad267b78fc1912"
    },
    {
      "id": "inplace_027_05_idx_v4_model_usage_quota",
      "checksum": "260ef3c41f57e088e8965b23be3f82c4fffdf2dd4862587963ce6d9c4003e3dd"
    },
    {
      "id": "inplace_027_06_idx_v4_model_usage_recovery",
      "checksum": "92c7fd0ac15fcf272eae5a80310465d17dd2136f95f1ce6e08225168a9580342"
    },
    {
      "id": "inplace_028_01_fk_v4_bridge_refresh_user",
      "checksum": "a8b6a574b97bfeb441141b936f918e39050ec851626297088d801c809bd65bc9"
    },
    {
      "id": "inplace_028_02_fk_v4_model_default_profile",
      "checksum": "40217ad8cef6fb12192e682367df632d0de959124bf2ecfbb52262c12fca32d9"
    },
    {
      "id": "inplace_028_03_fk_v4_capabilities_profile",
      "checksum": "54dc8ffc13663dbe094da52f07975fc238771bb0c0b2ffc905c7e314696e41ab"
    },
    {
      "id": "inplace_028_04_fk_v4_capabilities_verifier",
      "checksum": "7a03f10c10636b50e12bf664e44357c177b346fdd47da498a1f8dc8eba832d4b"
    },
    {
      "id": "inplace_028_05_fk_v4_model_usage_profile",
      "checksum": "87de27b5d91ed8b7b1baa6e7569af662dad23a94dbb282cb68b0eb21b573d7c6"
    },
    {
      "id": "inplace_029_01_usage_strategy_capacity",
      "checksum": "db10826a888ab9dd43ce62b2abae219cb7ee9e573ad42f31f2606e043f18ac76"
    },
    {
      "id": "inplace_030_01_fk_strategy_subscriptions_account",
      "checksum": "f5eed98904aa4443249629c2eca397ba155b559d73715ae73a7cc26d7c2a91cd"
    },
    {
      "id": "inplace_030_02_fk_strategy_subscriptions_user",
      "checksum": "30a8611c9ba0fb7d40b3fd63b400ab55a19165cc3bcde20544c7a335fc9fe4a9"
    },
    {
      "id": "inplace_035_01_account_root_promotion",
      "checksum": "6f468bae7f5d2a89c3cce2c60654680efd29a2bb7dc22579f3cb5af51c40fe93"
    },
    {
      "id": "inplace_036_01_terminal_account_bindings",
      "checksum": "5eeda88f7fe506d76786fb3e6cd656101f35dcdfc47686ff77947fc75bf48c0c"
    },
    {
      "id": "inplace_036_02_bridge_connection_sessions",
      "checksum": "ca8ea61962e3a384cc3573de55d622cfa3ae8dd923ac58187e861ba3b3bf01c0"
    },
    {
      "id": "inplace_037_01_observer_sources",
      "checksum": "2d6f7b35a4bd492756d0054a0d1ca7eb37b77f982aaa2d4ba2dc18531e7e02e3"
    },
    {
      "id": "inplace_037_02_observer_channels",
      "checksum": "22d7909156bd20413b33da623567467868268d11ff9fbaa78fae3635ae932d2b"
    },
    {
      "id": "inplace_037_03_observer_channel_accesses",
      "checksum": "65931ff886b59c797b75f0e0c497ee50273256353b91d3b014afeef0e05d34fa"
    },
    {
      "id": "inplace_037_04_trading_contexts",
      "checksum": "f8a18b842548ff6c990c851b19716f65867cdfa2a5b8febf41d54139c3da00c1"
    },
    {
      "id": "inplace_038_01_account_runtime_snapshots",
      "checksum": "c2aa18eff3045a59d2cc1045dd20de514b953744adcc301ed890ea9419f16e5b"
    },
    {
      "id": "inplace_038_02_market_quotes",
      "checksum": "2e097edff3a1aa1472454563af0ed7e1c4883abe5c7ea35ac91abe69bdcb523c"
    },
    {
      "id": "inplace_038_03_open_position_snapshots",
      "checksum": "31f2282998ee53c274a19336db01359065f9545f0587f98f16a8f81dd1149351"
    },
    {
      "id": "inplace_038_04_pending_order_snapshots",
      "checksum": "10c8c481140f7d763915e82bbc687fdcfa1e22a9d3f57a5e0ab3668d981b3f18"
    },
    {
      "id": "inplace_038_05_trading_projection_revisions",
      "checksum": "46aad19e8f4121c95a518a4b91893d684f0b915b2afe0b2acd1241f9ca657627"
    },
    {
      "id": "inplace_038_06_trading_projection_provenance_v4",
      "checksum": "1f61e79ce1407858928175af324d6925768037b25bef155b626e5a3516dc683e"
    },
    {
      "id": "inplace_039_01_legacy_candle_backfill_v4",
      "checksum": "5bacf20ca52e58c81353640b117762694dbb06ff6a3bde6db85838d85e6c5da8"
    },
    {
      "id": "inplace_039_02_market_candles_build_v4",
      "checksum": "b81e93421cb18e00f4e33cd80b82d29581cd6ebbca6bfd6ed28cfef8477bede6"
    },
    {
      "id": "inplace_039_03_legacy_candle_mappings_v4",
      "checksum": "2d0eab50b94c5921f3d4a5007ee1dfd985763c6658093d7ebfbf76c41f367dba"
    },
    {
      "id": "inplace_040_01_legacy_candle_promotion",
      "checksum": "39a5bc0342361fabeacae9643adb7f073a4aa76f8875715c6fe66b6fbc1f4a18"
    },
    {
      "id": "inplace_041_01_trading_context_changes_v4",
      "checksum": "9c6ebdd2085469655abd8ed45d89eb6f6b72f49566f065733d67661a87dee42e"
    },
    {
      "id": "inplace_042_01_observer_management_registry_seed",
      "checksum": "ff7ce1e81d6bbf7d6650930f200b865613eb35fcb972ae87206d43dbc0d95bfe"
    },
    {
      "id": "inplace_043_01_risk_policy_sets_v4",
      "checksum": "9e2139a0f833a85d9606042296f1c3185dfbcb331e0ab62a5f7c0c6c31b58abf"
    },
    {
      "id": "inplace_043_02_risk_policy_versions_v4",
      "checksum": "fdabafbbd3c7c1e6b3312c2fe369194b2e56232299642fbc7f6a8705ea491e91"
    },
    {
      "id": "inplace_043_03_risk_policy_sets_v4",
      "checksum": "a8bd3ef1c177d06dfb2a2c355c1a8ce3f961762274c5c9f9d37a774eaaa6f67a"
    },
    {
      "id": "inplace_043_04_risk_policy_change_items_v4",
      "checksum": "74cafba203bf45ca117cf33072b47c797a21cc54278214e4dc4744dbd2a395ce"
    },
    {
      "id": "inplace_043_05_account_risk_states",
      "checksum": "03deb6aa524b4a82b38ae3d5d8e5a66b29105dfc023f4bb29e6f8400c07be0d9"
    },
    {
      "id": "inplace_043_06_risk_state_events",
      "checksum": "74dd4a8595c3fcafc38810f699508b7cae375f2c77f301b42c5f35a835001f45"
    },
    {
      "id": "inplace_043_07_account_risk_summaries",
      "checksum": "f31b9a669f69a5abef9b5dc98de02e9f3e5831d7dd4558b2ef2c743b5272786f"
    },
    {
      "id": "inplace_043_08_risk_manual_releases",
      "checksum": "0d612bf20358b7990e64b4414340e6db42e091f7c4995bebf74a3e090ccaf825"
    },
    {
      "id": "inplace_044_01_risk_policy_write_receipts",
      "checksum": "4d12b48a9c2e1f3b82ab565ea034f630e142912c1481b2604f14162891036cef"
    },
    {
      "id": "inplace_045_01_instrument_collection_requests_v4",
      "checksum": "3793f61700344be5b925be6323d8077f5b2f9614041c96d3709e95209f5c6fdb"
    },
    {
      "id": "inplace_047_01_trade_history_sync_states_v4",
      "checksum": "1f911dec633b383bc9d5fc64f95d9dd149ede3ac1b249c14393d927de376aa00"
    },
    {
      "id": "inplace_047_02_terminal_history_orders_v4",
      "checksum": "56aa24ce1d90ec7657efbcc635537980665d6997e306a9a1e652210b655656c0"
    },
    {
      "id": "inplace_047_03_terminal_history_deals_v4",
      "checksum": "dd4c646d2ef8f5466575d1df442a3d6d2580cc798fb83a90cac5fdc175f5c9a7"
    },
    {
      "id": "inplace_047_04_account_trade_records_v4",
      "checksum": "f3e386a1c0ab92a787d9c29ea7acf7eb383c12414701e1210d67fbcac07c1251"
    },
    {
      "id": "inplace_047_05_account_trade_record_deals_v4",
      "checksum": "42e75af260f32db58843fe4b4912f11ab4670d619ea486555f32e577cf8fd93c"
    },
    {
      "id": "inplace_047_06_account_trade_attributions_v4",
      "checksum": "1ba929961b84056ab7ced903ba543055f1b4034a5b3fc9d1591718cfb769f2d0"
    },
    {
      "id": "inplace_047_07_account_trade_daily_summaries_v4",
      "checksum": "cad4de12886d27fa478be07e42a6414211cc14f1f241a5fda3db0581be71953b"
    },
    {
      "id": "inplace_047_08_account_trade_records_v4",
      "checksum": "03d32ee7c5e30e55de0f8b672e44242996eef0d4686b5a8243768d9c34e7e46a"
    },
    {
      "id": "inplace_047_09_account_trade_records_v4",
      "checksum": "08827a6fd85ef5fe121370ec373d72b4efe5bbd44e1d04986eebabc37702e238"
    },
    {
      "id": "inplace_047_10_terminal_history_deals_v4",
      "checksum": "3742722bf0ba89676325783657cbace8b1cf5b42ba3c7d0756a4cf3efab52556"
    },
    {
      "id": "inplace_047_11_account_trade_records_v4",
      "checksum": "8fbc8725f229c1429d21474af0cf2e433d6e1cae4246ebf3e811e8054e231503"
    },
    {
      "id": "inplace_046_01_terminal_history_order_provenance_v4",
      "checksum": "397ccc320ae5092bc2fa2a78e2feef43bed226a9c9049bdc22f37b6686c14bcf"
    },
    {
      "id": "inplace_051_01_terminal_history_collection_receipts_v4",
      "checksum": "a96ab1486a23a611bcb68a2999b39fada71d46ec747372ff95e997f61a1ace03"
    },
    {
      "id": "inplace_052_01_terminal_history_deal_provenance_v4",
      "checksum": "dc4a5a5ea8cee890a2a9522e38964d67249b500ed4a47884b9b18e6d75830d2a"
    },
    {
      "id": "inplace_053_01_history_collection_tasks_v4",
      "checksum": "053bbcb553430581114d4468300ebac95cabd2138a11dfba490b57ca31d68ad7"
    },
    {
      "id": "inplace_055_01_inference_snapshots_v4_build",
      "checksum": "ce0e97adfaa39c0f9fa3ddd79fae049549e981e702234cd74b9e657a06bd1784"
    },
    {
      "id": "inplace_055_02_inference_snapshot_payloads_v4_build",
      "checksum": "a5ef53fdc525deabb2fefcf62198231e66e9a012dad713282409303bd4b36ed3"
    },
    {
      "id": "inplace_055_03_ai_model_tasks_v4_build",
      "checksum": "f618152d2b5ca908bdb4d1381c603c3a961990665632135319912a89297c556b"
    },
    {
      "id": "inplace_055_04_ai_model_attempts_v4_build",
      "checksum": "96b157cb2ff3a3625cfa7889d7c932c9b3563431b773ce57b3141eabd6f18da3"
    },
    {
      "id": "inplace_055_05_ai_analysis_runs_v4_build",
      "checksum": "cc1cd7b4e1ac32ac58442b65710c9f899f59e6c43e740592bfbd6d6eb684d5ce"
    },
    {
      "id": "inplace_055_06_market_analyses_v4_build",
      "checksum": "776729f8ee82526d604420e59ef85f71de9b26c66ff84edf28dcb36b9dc6c423"
    },
    {
      "id": "inplace_055_07_market_analysis_payloads_v4_build",
      "checksum": "a3e54f8a9ef997aaa876da934397f1c43ddba8fb94dc07fd4fe7790800e71b61"
    },
    {
      "id": "inplace_055_08_ai_trader_runs_v4_build",
      "checksum": "5c95445dc546c397334e8a2ffbfb4e635477b48a92ad0ecc18d868e9fd1ad7cc"
    },
    {
      "id": "inplace_055_09_trade_decisions_v4_build",
      "checksum": "65f1f0822ec337d41c10941fca717227df752f0602936979a18c979383fb615e"
    },
    {
      "id": "inplace_055_10_trade_decision_payloads_v4_build",
      "checksum": "ff29c72bcf0d1f85b09e3c6a777814dba829888711ae2efeafda579247e5b0f7"
    },
    {
      "id": "inplace_055_11_risk_decisions_v4_build",
      "checksum": "ee31fb9916c024c12de50ef68c75bad458d42db474969cb7c30cbf45b3a992da"
    },
    {
      "id": "inplace_055_12_risk_decision_payloads_v4_build",
      "checksum": "d9c4a566a2d737fc25150c4b98ce77717e493bc1888acfb266426d315d794ba4"
    },
    {
      "id": "inplace_055_13_trade_decisions_v4_build",
      "checksum": "533d9abff439421bc4554dc9f37cbeec443431f78cb5ad036739818003317ece"
    },
    {
      "id": "inplace_057_01_market_quote_provenance",
      "checksum": "74ef5906ee5a9bfe65f055de3d05f527884306fe6da2c46683079a9037f4fab7"
    },
    {
      "id": "inplace_063_01_inference_root_promotion",
      "checksum": "4997a58f74344a89a82cc8184b0225f28f4b855f065e4ae075228ab349f38e31"
    },
    {
      "id": "inplace_064_01_execution_workflow",
      "checksum": "7108e6d65f9fcfaf66a0be5160f083615ec407e8b69ed4bc546fd3618d58d9e7"
    },
    {
      "id": "inplace_064_02_execution_workflow",
      "checksum": "0855e8d385a119549bfbd5f7be2bc66adf47f0064df5dd8458cc8867da9ec5a8"
    },
    {
      "id": "inplace_064_03_execution_workflow",
      "checksum": "3a0ef6a64eeee6e579f0e3d4f80437d4764adba2b99b3da1c3fb66b5c322ae1c"
    },
    {
      "id": "inplace_064_04_execution_workflow",
      "checksum": "796e3d3f6ff2444a2bc15e8f95f989d9564ab40013e28bf05dfa6d21d0d4d6a8"
    },
    {
      "id": "inplace_064_05_execution_workflow",
      "checksum": "e4b40ae2e0535e03ff0d8fa2804ddd116e65ec9b2a3baf7f8bdb34c495e4e106"
    },
    {
      "id": "inplace_064_06_execution_workflow",
      "checksum": "93c4de24033a00de8f74b2554f73049018a447bc79824a9155125a1174f77ada"
    },
    {
      "id": "inplace_064_07_execution_workflow",
      "checksum": "35f4516b02ee1e01be1b3fc231adafcd4bb37d0f72834f8e8cd1429eebfe8125"
    },
    {
      "id": "inplace_064_08_execution_workflow",
      "checksum": "ef34e593b046f774fd6dd94689c434a2b01ad94bc4bb9ca53fefb376c382c79b"
    },
    {
      "id": "inplace_064_09_execution_workflow",
      "checksum": "a9278aec076206be9e5537f7cabaf5f38a4f4ef418f74d132a860ccf60aded67"
    },
    {
      "id": "inplace_064_10_execution_workflow",
      "checksum": "3b788d80647052275e77864c74a0d965e06a4f1729a1236fafd69ab3b8b0fa1b"
    },
    {
      "id": "inplace_064_11_execution_workflow",
      "checksum": "aa3d6b3f8fe7854c0e86485ec95e3225919802a26a7813bd07a3c9a189fdb29f"
    },
    {
      "id": "inplace_064_12_execution_workflow",
      "checksum": "6becc406bcdb5e5ec990f96d3d9bc2f08134507c742de88a3743a56c25bb2aa0"
    },
    {
      "id": "inplace_064_13_execution_workflow",
      "checksum": "17691111e802c40466f27bade0808a84743eccbf23db071e9f49fb5dc22e5dc0"
    },
    {
      "id": "inplace_064_14_execution_workflow",
      "checksum": "d34cd043afe28b5453d6ef1917ccb5051e70427893f316cd1397e65a8efac357"
    },
    {
      "id": "inplace_064_15_execution_workflow",
      "checksum": "2dac56fe62f6d947e6b112ee30a86a5d3ea19210cfadfc96c1b72fcc338da2ea"
    },
    {
      "id": "inplace_064_16_execution_workflow",
      "checksum": "e108d77ae050d0007f7a5a6db8b591c5983905de4dee8635bc9ab87ab2ab728a"
    },
    {
      "id": "inplace_064_17_execution_workflow",
      "checksum": "5f04acf9770ca5bcd279147e2552ed86bd94afa1d4103ada42705444bcaa0bf7"
    },
    {
      "id": "inplace_064_18_execution_workflow",
      "checksum": "e56a2bbe2e118a4f5705606ad4e1608b4dc69ecfabf3a633cdeae604624f0ee9"
    },
    {
      "id": "inplace_064_19_execution_workflow",
      "checksum": "ff01ffa5d36e0ea1de6a7d5a19a20fb3b2ea7091d17f252ac3cf4689047a724c"
    },
    {
      "id": "inplace_064_20_execution_workflow",
      "checksum": "14fe718be4483500c3ef98084fcc6e1d9f56b9ce6dfe35750e2b86d1c6133274"
    },
    {
      "id": "inplace_064_21_execution_workflow",
      "checksum": "7c70e70293d43f57541349ac444ff80b288146a38aa2eb1bb0f47ab55a68aa05"
    },
    {
      "id": "inplace_064_22_execution_workflow",
      "checksum": "3f2ccaf13ebcea7ef92e8b32811088a960c166ee85494df61010ab858063bb7d"
    },
    {
      "id": "inplace_064_23_execution_workflow",
      "checksum": "26abd0f5cf6f8a29b62fe56111585ec895f1eb7387d24713515a68e90b54c1c1"
    },
    {
      "id": "inplace_064_24_execution_workflow",
      "checksum": "9e9599439f08ea66913a7634f296aa608285af894a85fccc52376d36c7a06bd6"
    },
    {
      "id": "inplace_064_25_execution_workflow",
      "checksum": "24f77ed9fee4086a9a188cd6edbafa41e108a994854a96482af2bf6d42f59698"
    },
    {
      "id": "inplace_064_26_execution_workflow",
      "checksum": "49463b1f15ace7be578c4b40a1e15fc7324090d6f694501332557e33994fe463"
    },
    {
      "id": "inplace_064_27_execution_workflow",
      "checksum": "97b2ea3036a46eb6a3b53e35f80184457827fa92d57ca5bcda6b87705219c4d0"
    },
    {
      "id": "inplace_064_28_execution_workflow",
      "checksum": "85fb72fd35cd20e00b35d409af07265b2faf6091df4778281dae230c58cbd536"
    },
    {
      "id": "inplace_064_29_execution_workflow",
      "checksum": "27aa7cdfeb7ab187bdeb83f96c7017921ea79a4a3d5c9130487f8b386be8f585"
    },
    {
      "id": "inplace_064_30_execution_workflow",
      "checksum": "9b93b941fff218335386361eb22d1a2bef304566ba80d4a9614651872e272632"
    },
    {
      "id": "inplace_064_31_execution_workflow",
      "checksum": "ad330a3cfc89cecd1f1f28147bd572d9d621b84be52bc5d656d517198613c536"
    },
    {
      "id": "inplace_064_32_execution_workflow",
      "checksum": "fbe3fd8f9c009d88dcf85ede5477005eed2d7ced7f33ab9484522da9592f2717"
    },
    {
      "id": "inplace_065_01_bridge_reconciliation_outbox_index",
      "checksum": "2405e421ac460bd6a8d482cdf381928e5b0ea21fc64950d30514b2c0b7ef008e"
    },
    {
      "id": "inplace_066_01_partial_close_parent_dispatches",
      "checksum": "34b9296c2c326a65e4ba9101a5b993c9219c3df54fcb383078fd33126cb34e83"
    },
    {
      "id": "inplace_067_01_strategy_write_receipts",
      "checksum": "37098d75740cd1ce219bacf64f84ea0b555e209e32a46e417d507abd1c67ccd1"
    },
    {
      "id": "inplace_068_01_review_runtime",
      "checksum": "38f37ded39779a0e0ac0e3d3f60fdbd01c39b45da08b76c6b669938494ea6879"
    },
    {
      "id": "inplace_068_02_review_runtime",
      "checksum": "2922a0c08b79bcdab4724723e5d14d4b6bb9eb681a1d3184527a68d6b6241699"
    },
    {
      "id": "inplace_068_03_review_runtime",
      "checksum": "b9801cfacaee4d44f23b8457786960fb20fe3aacc24882267829c4242f53d6e3"
    },
    {
      "id": "inplace_068_04_review_runtime",
      "checksum": "3f12d9fce766ad2fef8248aa7ed96c3eb3ff993acba34dd444642d02f22be75c"
    },
    {
      "id": "inplace_068_05_review_runtime",
      "checksum": "0cb3fdf6327ba2d17d5d7d15e1cd1eaec00e7e3cac6c8e67ce22659730a67a3a"
    },
    {
      "id": "inplace_068_06_review_runtime",
      "checksum": "1eb92cfa6a8bb8506dff381a175f000a3c5f5b28051e7c781be724fa8f3baf4f"
    },
    {
      "id": "inplace_068_07_review_runtime",
      "checksum": "70685b4dbefcecb458d1351cbd89b0a96de65c5475b28fc23569fb80553bc5d3"
    },
    {
      "id": "inplace_068_08_review_runtime",
      "checksum": "e5374bdd934eee9514a9f881da7f2701973825df10a80429ce04a3eadbdbb153"
    },
    {
      "id": "inplace_068_09_review_runtime",
      "checksum": "c1eae06d6467176d790996179f50a3a62afec5b17a488630c15774055cac9771"
    },
    {
      "id": "inplace_068_10_review_runtime",
      "checksum": "75820b9c2ee56416d317b9b7c83168f1cefd2f05936976a779da6a272be83532"
    },
    {
      "id": "inplace_068_11_review_runtime",
      "checksum": "7b0987c4ff0edbc5c2f0bb57c474019251463c363272779042304332a607790b"
    },
    {
      "id": "inplace_068_12_review_runtime",
      "checksum": "cc895b515fca2b863eaa0a3e3b8892ed8830ece3520a96dce73fd24cf66dd99b"
    },
    {
      "id": "inplace_068_13_review_runtime",
      "checksum": "369efd3e56455a8bdbc06c51a5fc34e695be2369366073d931858976c6d97b18"
    },
    {
      "id": "inplace_069_review_history",
      "checksum": "c8ddca367579a6c698ad78c0d489776c9b30b7f320299920036c38cf0a2e9a1e"
    },
    {
      "id": "inplace_070_review_history",
      "checksum": "e188881157632d48560a72c044a125bba808b2be27c89097dc616f9da7681418"
    },
    {
      "id": "inplace_071_01_review_archive",
      "checksum": "bf0fe8c0fe724533e913dd034c1812e8299feaa1501f094ef0ff5a5f88516f7f"
    },
    {
      "id": "inplace_071_02_review_archive",
      "checksum": "5754a058f07704f7162852e63e624be2f1cb29fe3b7a88b6fa29780bf1f1ce10"
    },
    {
      "id": "inplace_071_03_review_archive",
      "checksum": "a20b8fa43f97e4d22be0e05cc5cddc271995c3a0616807a9e7627c801ee50902"
    },
    {
      "id": "inplace_072_01_instrument_snapshot",
      "checksum": "05e143875fbfcd47ffcf6f24502b0e469d10c215f5b74baa4dcc1c5b59f91f15"
    },
    {
      "id": "inplace_073_01_manual_candidate_evidence",
      "checksum": "839131cd305c826e759841e6b625904cd43681bdd1a1e2ad5c3350c1e36d51b9"
    },
    {
      "id": "inplace_074_01_manual_candidate_task",
      "checksum": "cf7dd27e5550d545d9491ec421cf3705ad3b7d72135e3fab285d88ed2507c6f7"
    },
    {
      "id": "inplace_075_01_system_review_task",
      "checksum": "77e23401ac5a0ad7f020849e0991ce0dfe3f433fac169494f05063dc4055684e"
    },
    {
      "id": "inplace_076_01_clock_observation",
      "checksum": "8ad9e17091163dc0aaa50e1c4c93449cc4fb1f7e7d84ad1f4e369b70a75a793d"
    },
    {
      "id": "inplace_077_01_period_workflow",
      "checksum": "40639c61adfddad1faadc36ade4e2ef749dd930ed5a247adb859cc1b4f6aab67"
    },
    {
      "id": "inplace_078_01_memory_audit_completion",
      "checksum": "8ea6897cccaee075c6a02b939413dcb1ffcc7f9c3c51af6faceca46b398bbae2"
    },
    {
      "id": "inplace_079_01_entry_event_claims",
      "checksum": "eb33a891e6111a84547bb3d2a84b7035aef5d58b0782d56ff6f5978efc54cd0c"
    },
    {
      "id": "inplace_080_01_bridge_installation",
      "checksum": "324beea7c8c5abfce29bc3e3846b883bdabe13871c3de96ee52b5d617c16534b"
    },
    {
      "id": "inplace_080_02_bridge_installation",
      "checksum": "31eba700cda90b5db8b85f70ec1a1f36d75636dad30f374f676f3c34b91b83b4"
    },
    {
      "id": "inplace_080_03_bridge_installation",
      "checksum": "e0a3d977274ebc560191a50b36013768562b3164f5c37e72837f4d943a93bf67"
    },
    {
      "id": "inplace_080_04_bridge_installation",
      "checksum": "9faf5a2ff4c70a884c7a87b18f41d4c3efb7131ce9df83bc95e9905f6e57c6b9"
    },
    {
      "id": "inplace_080_01a_limits_collation_correction",
      "checksum": "1eb10ba8b785fe139d60753f4e0d5a2f9429b4be785352240e3fc04119310c9c"
    },
    {
      "id": "inplace_081_01_market_source_selections",
      "checksum": "e7e5ba695eba1502926f6457ab280b05fbda90d9aa71a09040edb02559f4199e"
    },
    {
      "id": "inplace_082_01_model_configuration_receipts",
      "checksum": "41bf01d4f6cd70a9269a622707b51a13fd7a40a52659ce19b9fc718e4c15b56c"
    },
    {
      "id": "inplace_083_01_model_assignments",
      "checksum": "f1602f6d728a715d580f75266d5502614a389cbee04865036e93e2cc9810fe91"
    },
    {
      "id": "inplace_084_01_strategy_trader_receipt_action",
      "checksum": "22855769b1512df934b2cc662bca0fbd49e1502c9b11bd0c375e332a6ba19cda"
    },
    {
      "id": "inplace_085_01_account_daily_risk_baselines",
      "checksum": "6690f799003b6172925c816cfa59e8e065d938012e986616f53fcded3d9af62d"
    },
    {
      "id": "inplace_086_01_risk_reapproval",
      "checksum": "24d83c62967b96c0f8c8a94a135aadad190e62f4c06a2ccd232575197a92d520"
    },
    {
      "id": "inplace_087_01_strategy_combination_receipt_actions",
      "checksum": "3a939abbfaaaebf34be8b1bb40faaa7a90e4601ecba337c24e74afc0592b5d94"
    }
  ],
  "tables": [
    {
      "table": "ai_analysis_runs",
      "schemaSha256": "99ae8cd0dba778b18a31bb6d59efbaa4ad27d09078a485b334eec6aec91b190f"
    },
    {
      "table": "ai_model_profiles",
      "schemaSha256": "df9835e57f67df0e4c19fc278553b916bdad97d3038bc2a55fc9f003a760e4e9"
    },
    {
      "table": "ai_model_tasks",
      "schemaSha256": "933f89658bbabee273375e2a74879ddacb105e27f167717e4eb16d069703e1a8"
    },
    {
      "table": "ai_trader_runs",
      "schemaSha256": "1925ce985a97da142982de85d57b555f5e247dcbc0fa428d8aca2db234601247"
    },
    {
      "table": "bridge_command_events_v4",
      "schemaSha256": "3709fe89be1cc6e928e2fee2adc844267feac96cd6363888e95b598af16b1fe0"
    },
    {
      "table": "bridge_command_payloads_v4",
      "schemaSha256": "ad78a41ddeed4971e3f56058a049c6c1cc50519d8f3c204d343d4856e8c14d9f"
    },
    {
      "table": "bridge_command_results_v4",
      "schemaSha256": "3222d01e633605e65d6e7f07636824f56a41b35aab608732d3dfdb7a73feaccc"
    },
    {
      "table": "bridge_commands_v4",
      "schemaSha256": "ea516a73bd3a1078a91eec0ba425fb2036dac48ea91ea0742bca12475a027fd1"
    },
    {
      "table": "bridge_installation_authorizations",
      "schemaSha256": "c2ed0914f29567101f436149c57ceecef5f40dbc1da5d8aca600a0963ea4452d"
    },
    {
      "table": "bridge_installation_request_limits",
      "schemaSha256": "6da63196c53d533c7b15b29b1277760c724dc81339a4de882c705a5c70d99ab9"
    },
    {
      "table": "bridge_installation_requests",
      "schemaSha256": "fe386e3944b8ebb336e84242695acb840b34e5a0cdf0f3b976a1380a603b6fe7"
    },
    {
      "table": "bridge_refresh_sessions",
      "schemaSha256": "da48089338692c567efd7f4760796932967bb9f30d033581ed02e483dca685d5"
    },
    {
      "table": "bridge_trade_state_snapshots_v4",
      "schemaSha256": "5f241b3a6bc90f2ad9ab8172ee67ac7e921fe3f0910f690c21afa48c0d167ab8"
    },
    {
      "table": "data_migration_checkpoints",
      "schemaSha256": "63b25e568b62520e5b4da354f5dc2d6ac7914568a9e6cb8925a88bef74023ffb"
    },
    {
      "table": "data_migration_runs",
      "schemaSha256": "7aa4ec51dfbb2b317ee2facf4a6de7401e1d3a82379f15317aa6d396157ac7cb"
    },
    {
      "table": "execution_distribution_targets",
      "schemaSha256": "4bc4089091c7515c22042c2297b44ed665ad136a1f3cf1bf81457ef51ed2ff6a"
    },
    {
      "table": "execution_distributions",
      "schemaSha256": "2e9df186d3342eec7ddba605eca4db3742c2bdc9ea5a83d00750a9139366fdaa"
    },
    {
      "table": "execution_intent_events",
      "schemaSha256": "14968fd862f69892c961bf2ec7b3f9857180d86eb3db44e2c25a3af8f6a8ebe7"
    },
    {
      "table": "execution_intent_payloads",
      "schemaSha256": "34e077334ceac64debadcf051441d15d025b83774dc41369e67416e6cb3a206a"
    },
    {
      "table": "execution_intents",
      "schemaSha256": "168dc7796ba11005402af8b04925f5e701a578eb897dfbdab01b0aaaa1ab1bb6"
    },
    {
      "table": "execution_outcomes",
      "schemaSha256": "8ef89d9bbc8eb90a1892225f891045b0267359487dc612a3c3e6d510869df1f3"
    },
    {
      "table": "history_collection_tasks_v4",
      "schemaSha256": "fb93925874e5c72a55ef3763248ccad98287fc9c2e24e556bcb8c95b1d639986"
    },
    {
      "table": "inference_entry_event_claims_v4",
      "schemaSha256": "48d667b16668ac0cd0a60449bbc7cc21e559ca4581856b5e43907882a3758763"
    },
    {
      "table": "inference_snapshots",
      "schemaSha256": "57a6c1852cdd8b6ec7a7bbb067338c04580a0c24b7666f0c8b621ae6b7bc5d45"
    },
    {
      "table": "manual_candidate_tasks_v4",
      "schemaSha256": "be3b41f47617de644a57e31e29e4aa0a4c7fb862fa5c80c7f7f45397ddab127c"
    },
    {
      "table": "manual_review_candidate_evidence_v4",
      "schemaSha256": "a7dc7f8258a75b0ba972c75c9ffcc318bb1bea2f08afbbbfcc531bd7a0359cd5"
    },
    {
      "table": "manual_review_candidates_v4",
      "schemaSha256": "eaa470328160a246c08ccbc05847cd1ca3610e77fc012a60f8785bfdf2750df6"
    },
    {
      "table": "market_analyses",
      "schemaSha256": "b2b53e9536154b4fdfe1921474c21b412a730048053a97789e4396b3d0a9cc90"
    },
    {
      "table": "market_instrument_snapshots",
      "schemaSha256": "d7a7b28b85efcd6f0cd87f67594e38a7ca2de80ee1dbb103a545e86d2782dbe3"
    },
    {
      "table": "operation_events",
      "schemaSha256": "625c106c9fa011e1f598573dd9d7a7593f30038059e6456e085352963af6781d"
    },
    {
      "table": "operations",
      "schemaSha256": "04a0d98abdb3bc6b097a66c89851447761854f1abd3e8db819a73824e25298df"
    },
    {
      "table": "outbox_events",
      "schemaSha256": "3ed765b718156c32b8be2aa2e085fcb044ce4db284a3b9e09970f1f43441187c"
    },
    {
      "table": "partial_close_parent_dispatches_v4",
      "schemaSha256": "ec1cd32ff68f35de69f091c6a6de10c89bb6e4123aa83fad9c91a450189aa4e6"
    },
    {
      "table": "partial_close_workflow_events_v4",
      "schemaSha256": "a5d98021391a050eafa7158ecc436a9e62c1f6534fc4823824278973d2e43445"
    },
    {
      "table": "partial_close_workflows_v4",
      "schemaSha256": "e91b31a3c1105758624bb0af12e49f910d653dcabbf77a9e19eb4d06f428d50d"
    },
    {
      "table": "period_review_workflows_v4",
      "schemaSha256": "7c91ad37d4748a6a5f3778583f762f9ad1c2c2fe68e83161e30612612caa9ef4"
    },
    {
      "table": "position_protection_commands_v4",
      "schemaSha256": "de787b65feb9a6777c96ba4901ff04c9e36fdb3b0fe1cc7af472393d296f8fdd"
    },
    {
      "table": "position_protection_dispatches_v4",
      "schemaSha256": "45e2da9dcba9ece2033d37eb0d147b5ca8cfb811841e443259a873fc545a9cd6"
    },
    {
      "table": "position_protection_outcomes_v4",
      "schemaSha256": "0a9bd355e75dd013705e13b83e48e101643fe6461293a0e7dbd2bace73fb80ef"
    },
    {
      "table": "position_protection_reviews_v4",
      "schemaSha256": "6fd0b47583e11df0d2b5e4a362c0737a94d989e6224b0da04a62ec810e4ce4ca"
    },
    {
      "table": "position_protection_unissued_expiries_v4",
      "schemaSha256": "a93b6a028fec9ddfdbb4884e8947842243c746f468ffd39903eed89f922c35d7"
    },
    {
      "table": "review_case_history_v4",
      "schemaSha256": "789a86770d958be2ed412c3e784029b2495fb4b6fb628900545adc1efcdb4ef4"
    },
    {
      "table": "review_case_sources_v4",
      "schemaSha256": "da2af96137367837bddc70c22307587155b73b32ae01f144cd306de99987ab96"
    },
    {
      "table": "review_cases_v4",
      "schemaSha256": "556bc98d54a25686dc3749c0f6dd31dfc1da0f0490780449d14b378ec867c1ed"
    },
    {
      "table": "review_evidence_payloads_v4",
      "schemaSha256": "f8efbce2034139afcac175c9cbe0db4efa2664746f4b5ce00457062aa7edd2f6"
    },
    {
      "table": "review_job_events_v4",
      "schemaSha256": "97a69fddc7fa0e6b2419b42da87967574542ed5822f3646366d391356dbe0cba"
    },
    {
      "table": "review_jobs_v4",
      "schemaSha256": "56d96fe23f81b262b04a1db72f55d699994a7ff3d1af5c099289f19c7569f9a6"
    },
    {
      "table": "review_model_attempts_v4",
      "schemaSha256": "519785a5d0dd90b906428633b26a727250ae0a0b270f73eca886dbb71d6d6c95"
    },
    {
      "table": "review_user_states_v4",
      "schemaSha256": "3246541397522add077362fa1c1b6e2ce3047ee7736e03095929b0ddd6d93553"
    },
    {
      "table": "review_version_payloads_v4",
      "schemaSha256": "c9f0d0e7b6b69766ab2dfb606433279489a6710d5258ba69e4b5353eb91fc2f1"
    },
    {
      "table": "review_versions_v4",
      "schemaSha256": "82edff9199c58131a64e0e758c379e5bd31b5451b59956e0d430e590e52bf500"
    },
    {
      "table": "review_write_receipts_v4",
      "schemaSha256": "21b440b19fdf9706c97ba9f7c5bf3c42b4c401a6d6c8863c07a56ba6bc44b45c"
    },
    {
      "table": "risk_decisions_v4",
      "schemaSha256": "6814914360c7e69519184c6d3fc9f731f1c93a8ecf1f895455c5b4c59d77e6c4"
    },
    {
      "table": "risk_manual_releases",
      "schemaSha256": "d079f1d3ec62adf64e27a72097437d122b871812e33d4595a5eed89f555d0fc4"
    },
    {
      "table": "risk_policy_sets_v4",
      "schemaSha256": "7a931972f59546b3b5b4ff7070672d9611507d76fdd3c0c12384bc18ae443718"
    },
    {
      "table": "risk_policy_versions_v4",
      "schemaSha256": "dfa7a7777c56b293e5a13842c071c401f1034962255bf373daed3aeba8cb880d"
    },
    {
      "table": "risk_reservation_events_v4",
      "schemaSha256": "1f6f0f55faea7da672be72336479deefdcfefd5889283b4901adc74fd66f9745"
    },
    {
      "table": "risk_reservations_v4",
      "schemaSha256": "717b4dcd2492425ef023163e8f3ed9e6eb3f4f7a25223d935994d8591b73c837"
    },
    {
      "table": "strategies",
      "schemaSha256": "8435f65723f4c195d0b8767fa7cf1d9eefa4eae7ca20177d141946fcd8768bab"
    },
    {
      "table": "strategy_memory_injection_logs_v4",
      "schemaSha256": "9bf190abcd230aab2609603405b722b51c9ae86b5cd09b6a8d9762b05bc34474"
    },
    {
      "table": "strategy_memory_libraries_v4",
      "schemaSha256": "0d735d68cdaf5675252cd37fcc7b54f25e344b85f37f84f3ba3d82ee887c4935"
    },
    {
      "table": "strategy_memory_library_revisions_v4",
      "schemaSha256": "d99ece45edc693c8033fa0379007f0d18628a98bd8e2d46f816c3539235675d5"
    },
    {
      "table": "strategy_memory_pending_updates_v4",
      "schemaSha256": "779f7a2a0761f9602dc4f52e89224ba3211b023a42c4defd4da78a56415dcca9"
    },
    {
      "table": "strategy_subscriptions",
      "schemaSha256": "981f91847533c8647a7c885c453ad2396e46ce9e8bbb6fd79bfff87465271d64"
    },
    {
      "table": "strategy_versions",
      "schemaSha256": "768295142175363f8f381a4bc6b68d56ec1171e5e9211bf7ffa5a2ec90db31ee"
    },
    {
      "table": "strategy_write_receipts_v4",
      "schemaSha256": "484029b5a70bf77f84f65f43523c025ede04ab56021323dff5b23a5f32c03735"
    },
    {
      "table": "subscription_execution_preferences",
      "schemaSha256": "fc36dc644c8d1b1bc14c9581999e7bb704a13b6f69d729ec5b1d0f747d11459a"
    },
    {
      "table": "subscription_schedules",
      "schemaSha256": "1a350a9d1a8e575a765752a952fa693c649a19d6d2d504e8c87379faec517913"
    },
    {
      "table": "system_review_tasks_v4",
      "schemaSha256": "67f93c41b85b2cdffdc93c7152eb4fcb36486678b65c2c788d06b2218a4125a8"
    },
    {
      "table": "terminal_clock_observations_v4",
      "schemaSha256": "a6c7f8eda5503df89b7d9f1c3ce3279bb443e57b0ac5fee36fff8fd846020dd2"
    },
    {
      "table": "terminal_history_collection_receipts_v4",
      "schemaSha256": "40127aca381788dc62367d114e11f142e90dac9d9283b77a0079500d4670fe86"
    },
    {
      "table": "terminal_profiles",
      "schemaSha256": "e796241d28dd63d6ee3b60b846184bc9f2b73c574dd33dd31240c873d604a13c"
    },
    {
      "table": "trade_decisions",
      "schemaSha256": "30af91d08c09edaed47e1d9d6976c496acee5c43b1d4f56cfabb850c14621632"
    },
    {
      "table": "trading_account_ownership_intervals",
      "schemaSha256": "f9c72a58a6c16ac46b55e87e0ba3bcc21a7d53e2673adc3e357d0d28cdc29e76"
    },
    {
      "table": "trading_accounts",
      "schemaSha256": "310c81125e03d9712a669a383bfd2914a6b9dde5758153b5baf802f441dce01c"
    },
    {
      "table": "user_execution_commands",
      "schemaSha256": "d2d86a2bdb4684bea8617309f26ccbffe503ae13d268d200b4eefed50ffb4346"
    },
    {
      "table": "users",
      "schemaSha256": "cac027f809fae6396dd31254f9e3ec1e632158b6f64784540def3635985f4ffc"
    }
  ]
} as const
