// Generated by scripts/generate-instrument-schema-readiness.mjs; do not edit.
export const instrumentCollectionSchema = {
  "steps": [
    {
      "id": "inplace_045_01_instrument_collection_requests_v4",
      "checksum": "3793f61700344be5b925be6323d8077f5b2f9614041c96d3709e95209f5c6fdb"
    }
  ],
  "tables": [
    {
      "table": "instrument_collection_requests_v4",
      "schemaSha256": "cb4bff96b530f771a59c7ade7c29654cfbe05579552ec23a9b09f1c2b89e103a"
    }
  ]
} as const
