// Generated by scripts/generate-history-task-schema-readiness.mjs; do not edit.
export const historyTaskSchema = {
  "step": {
    "id": "inplace_053_01_history_collection_tasks_v4",
    "checksum": "053bbcb553430581114d4468300ebac95cabd2138a11dfba490b57ca31d68ad7"
  },
  "table": {
    "table": "history_collection_tasks_v4",
    "schemaSha256": "fb93925874e5c72a55ef3763248ccad98287fc9c2e24e556bcb8c95b1d639986"
  }
} as const
