// Generated by scripts/generate-history-collection-schema-readiness.mjs; do not edit.
export const historyCollectionSchema = {
  "step": {
    "id": "inplace_051_01_terminal_history_collection_receipts_v4",
    "checksum": "a96ab1486a23a611bcb68a2999b39fada71d46ec747372ff95e997f61a1ace03"
  },
  "table": {
    "table": "terminal_history_collection_receipts_v4",
    "schemaSha256": "40127aca381788dc62367d114e11f142e90dac9d9283b77a0079500d4670fe86"
  }
} as const
