// Generated by scripts/generate-history-deal-schema-readiness.mjs; do not edit.
export const historyDealSchema = {
  "step": {
    "id": "inplace_052_01_terminal_history_deal_provenance_v4",
    "checksum": "dc4a5a5ea8cee890a2a9522e38964d67249b500ed4a47884b9b18e6d75830d2a"
  },
  "table": {
    "table": "terminal_history_deal_provenance_v4",
    "schemaSha256": "f083f991959950c75a250645dd39fe49df0c02408c2e19abd29dd9cf88f38fb2"
  }
} as const
